import sys
from PySide6.QtCore import QCoreApplication, QMetaObject, QRect, QSize
from PySide6.QtGui import *
from PySide6.QtWidgets import *
from PySide6 import QtCore, QtGui, QtWidgets

class Ui_MainWindow(QMainWindow):
    def setupUi(self, MainWindow, Form):

        #Launching the Main Window
        if not MainWindow.objectName():
            MainWindow.setObjectName(u"MainWindow")
        MainWindow.resize(800, 400)
        MainWindow.setTabletTracking(True)
        MainWindow.setAutoFillBackground(False)
        MainWindow.setStyleSheet(u"background-color:rgb(241, 251, 249)")
        MainWindow.setAnimated(True)
        self.centralwidget = QWidget(MainWindow)
        self.centralwidget.setObjectName(u"centralwidget")
        self.label2 = QLabel(self.centralwidget)
        self.label2.setObjectName(u"label2")
        self.label2.setGeometry(QRect(50, 50, 631, 171))
        self.label2.setPixmap(QPixmap(u"ricemate.png"))
        self.pushButton = QtWidgets.QPushButton(parent = self.centralwidget)
        self.pushButton.setObjectName(u"pushButton")
        self.pushButton.setGeometry(QRect(30, 230, 721, 121))
        font = QFont()
        font.setPointSize(28)
        self.pushButton.setFont(font)
        self.pushButton.setStyleSheet(u"color: rgb(33, 123, 88);")
        self.pushButton.setAutoRepeat(True)
        self.pushButton.setFlat(True)
        MainWindow.setCentralWidget(self.centralwidget)
        self.statusbar = QStatusBar(MainWindow)
        self.statusbar.setObjectName(u"statusbar")
        MainWindow.setStatusBar(self.statusbar)


        #Choose your rice
        
        if not Form.objectName():
            Form.setObjectName(u"Form")
        self.label = QLabel(Form)
        self.label.setObjectName(u"label")
        self.label.setGeometry(QRect(290, 40, 231, 41))
        font = QFont()
        font.setPointSize(24)
        self.label.setFont(font)
        self.label.setStyleSheet(u"color: rgb(33, 123, 88);")
        self.label_2 = QLabel(Form)
        self.label_2.setObjectName(u"label_2")
        self.label_2.setGeometry(QRect(80, 260, 111, 41))
        font1 = QFont()
        font1.setPointSize(18)
        self.label_2.setFont(font1)
        self.label_2.setStyleSheet(u"color: rgb(33, 123, 88);")
        self.label_3 = QLabel(Form)
        self.label_3.setObjectName(u"label_3")
        self.label_3.setGeometry(QRect(240, 260, 141, 41))
        self.label_3.setFont(font1)
        self.label_3.setStyleSheet(u"color: rgb(33, 123, 88);")
        self.label_4 = QLabel(Form)
        self.label_4.setObjectName(u"label_4")
        self.label_4.setGeometry(QRect(450, 260, 91, 41))
        self.label_4.setFont(font1)
        self.label_4.setStyleSheet(u"color: rgb(33, 123, 88);")
        self.label_5 = QLabel(Form)
        self.label_5.setObjectName(u"label_5")
        self.label_5.setGeometry(QRect(650, 260, 61, 41))
        self.label_5.setFont(font1)
        self.label_5.setStyleSheet(u"color: rgb(33, 123, 88);")
        self.label_6 = QLabel(Form)
        self.label_6.setObjectName(u"label_6")
        self.label_6.setGeometry(QRect(100, 310, 81, 21))
        font2 = QFont()
        font2.setPointSize(12)
        self.label_6.setFont(font2)
        self.label_6.setStyleSheet(u"color: rgb(33, 123, 88);")
        self.label_7 = QLabel(Form)
        self.label_7.setObjectName(u"label_7")
        self.label_7.setGeometry(QRect(270, 310, 81, 21))
        self.label_7.setFont(font2)
        self.label_7.setStyleSheet(u"color: rgb(33, 123, 88);")
        self.label_8 = QLabel(Form)
        self.label_8.setObjectName(u"label_8")
        self.label_8.setGeometry(QRect(460, 310, 81, 21))
        self.label_8.setFont(font2)
        self.label_8.setStyleSheet(u"color: rgb(33, 123, 88);")
        self.label_9 = QLabel(Form)
        self.label_9.setObjectName(u"label_9")
        self.label_9.setGeometry(QRect(640, 310, 81, 21))
        self.label_9.setFont(font2)
        self.label_9.setStyleSheet(u"color: rgb(33, 123, 88);")
        self.pushButton1 = QPushButton(Form)
        self.pushButton1.setObjectName(u"pushButton")
        self.pushButton1.setGeometry(QRect(60, 120, 141, 131))
        icon = QIcon()
        icon.addFile(u"F:/Users/Dann Joseph/Desktop/2022 North Trip/Vigan/20220930_161006.jpg", QSize(), QIcon.Normal, QIcon.Off)
        self.pushButton1.setIcon(icon)
        self.pushButton1.setIconSize(QSize(140, 140))
        self.pushButton2 = QPushButton(Form)
        self.pushButton2.setObjectName(u"pushButton_2")
        self.pushButton2.setGeometry(QRect(240, 120, 141, 131))
        icon1 = QIcon()
        icon1.addFile(u"F:/Users/Dann Joseph/Desktop/old photos/IMG_20180211_200111.jpg", QSize(), QIcon.Normal, QIcon.Off)
        self.pushButton2.setIcon(icon1)
        self.pushButton2.setIconSize(QSize(181, 181))
        self.pushButton3 = QPushButton(Form)
        self.pushButton3.setObjectName(u"pushButton_3")
        self.pushButton3.setGeometry(QRect(420, 120, 141, 131))
        icon2 = QIcon()
        icon2.addFile(u"F:/Users/Dann Joseph/Desktop/2022 North Trip/Pagudpod/20220930_200743.jpg", QSize(), QIcon.Normal, QIcon.Off)
        self.pushButton3.setIcon(icon2)
        self.pushButton3.setIconSize(QSize(194, 191))
        self.pushButton4 = QPushButton(Form)
        self.pushButton4.setObjectName(u"pushButton_4")
        self.pushButton4.setGeometry(QRect(600, 120, 141, 131))
        icon3 = QIcon()
        icon3.addFile(u"F:/Users/Dann Joseph/Desktop/old photos/IMG_20180211_200219.jpg", QSize(), QIcon.Normal, QIcon.Off)
        self.pushButton4.setIcon(icon3)
        self.pushButton4.setIconSize(QSize(195, 140))

        self.retranslateUi(MainWindow)

        QtCore.QMetaObject.connectSlotsByName(MainWindow)
    # setupUi

    def retranslateUi(self, MainWindow):
        MainWindow.setWindowTitle(QCoreApplication.translate("MainWindow", u"MainWindow", None))
        self.label2.setText("")
        self.pushButton.setText(QCoreApplication.translate("MainWindow", u"Tap to order", None))
        Form.setWindowTitle(QCoreApplication.translate("Form", u"Form", None))
        self.label.setText(QCoreApplication.translate("Form", u"Select your rice", None))
        self.label_2.setText(QCoreApplication.translate("Form", u"Dinorado", None))
        self.label_3.setText(QCoreApplication.translate("Form", u"Sinandomeng", None))
        self.label_4.setText(QCoreApplication.translate("Form", u"Jasmine", None))
        self.label_5.setText(QCoreApplication.translate("Form", u"NFA", None))
        self.label_6.setText(QCoreApplication.translate("Form", u"P. 52.00", None))
        self.label_7.setText(QCoreApplication.translate("Form", u"P. 45.00", None))
        self.label_8.setText(QCoreApplication.translate("Form", u"P. 47.00", None))
        self.label_9.setText(QCoreApplication.translate("Form", u"P. 57.00", None))
        self.pushButton.setText("")
        self.pushButton2.setText("")
        self.pushButton3.setText("")
        self.pushButton4.setText("")
    
    # retranslateUi

    def setThesisUIform(self):
        self.label2.show()
        self.pushButton.show()
        self.pushButton.clicked.connect(self.setThesisUIform1)
        self.label.show()
        self.pushButton1.hide()
        self.pushButton2.hide()
        self.pushButton3.hide()
        self.pushButton4.hide()
        self.label.hide()
        self.label_2.hide()


    def setThesisUIform1(self):
        self.label2.hide()
        self.pushButton.hide()
        self.label.show()
        self.pushButton1.show()
        self.pushButton2.show()
        self.pushButton3.show()
        self.pushButton4.show()
        self.label.show()
        self.label_2.show()


        



if __name__ == "__main__":
    app = QtWidgets.QApplication(sys.argv)
    MainWindow = QtWidgets.QMainWindow()
    Form = QtWidgets.QMainWindow()
    ui = Ui_MainWindow()
    ui.setupUi(MainWindow, Form)
    MainWindow.show()
    sys.exit(app.exec())