import sys
from PySide6.QtCore import QCoreApplication, QMetaObject, QRect, QSize
from PySide6.QtGui import *
from PySide6.QtWidgets import *
from PySide6 import QtCore, QtGui, QtWidgets
from ui_thesisUIform2 import Ui_Form

class Ui_MainWindow(QMainWindow):

    def setupUi(self, MainWindow):

        #Launching the Main Window
        if not MainWindow.objectName():
            MainWindow.setObjectName(u"MainWindow")
        self.setWindowTitle("Grainmate")
        MainWindow.resize(800, 400)
        MainWindow.setTabletTracking(True)
        MainWindow.setAutoFillBackground(False)
        MainWindow.setStyleSheet(u"background-color:rgb(241, 251, 249)")
        MainWindow.setAnimated(True)

        #Landing Page
        self.centralwidget = QWidget(MainWindow)
        self.centralwidget.setObjectName(u"centralwidget")
        self.label2 = QLabel(self.centralwidget)
        self.label2.setObjectName(u"label2")
        self.label2.setGeometry(QRect(50, 50, 631, 171))
        self.label2.setPixmap(QPixmap(u"ricemate.png"))
        self.pushButton = QtWidgets.QPushButton(parent = self.centralwidget)
        self.pushButton.setObjectName(u"pushButton")
        self.pushButton.setText("Tap to continue:")
        self.pushButton.setStyleSheet(u"color: rgb(0,0,0)")
        self.pushButton.setGeometry(QRect(30, 230, 721, 121))
        self.pushButton.clicked.connect(self.setOrderPage)
        font = QFont()
        font.setPointSize(28)
        self.pushButton.setFont(font)
        self.pushButton.setStyleSheet(u"color: rgb(33, 123, 88);")
        self.pushButton.setAutoRepeat(True)
        self.pushButton.setFlat(True)
        MainWindow.setCentralWidget(self.centralwidget)

        #OrderForm
        font = QFont()
        font.setPointSize(24)
        self.orderLabel = QLabel(self.centralwidget)
        self.orderLabel.setObjectName(u"orderLabel")
        self.orderLabel.setGeometry(QRect(290, 40, 231, 41))
        self.orderLabel.setStyleSheet(u"color: rgb(33, 123, 88);")
        self.orderLabel.setText("Select your Rice")
        self.orderLabel.setFont(font)
        self.orderLabel.hide()
        
        font1 = QFont()
        font1.setPointSize(18)
        self.orderLabel2 = QLabel(self.centralwidget)
        self.orderLabel2.setObjectName(u"orderLabel2")
        self.orderLabel2.setGeometry(QRect(80, 260, 111, 41))
        self.orderLabel2.setFont(font1)
        self.orderLabel2.setStyleSheet(u"color: rgb(33, 123, 88);")
        self.orderLabel2.setText("Dinorado")
        self.orderLabel2.hide()
        self.orderLabel3 = QLabel(self.centralwidget)
        self.orderLabel3.setObjectName(u"orderLabel3")
        self.orderLabel3.setGeometry(QRect(240, 260, 151, 41))
        self.orderLabel3.setFont(font1)
        self.orderLabel3.setStyleSheet(u"color: rgb(33, 123, 88);")
        self.orderLabel3.setText("Sinandomeng")
        self.orderLabel3.hide()
        self.orderLabel4 = QLabel(self.centralwidget)
        self.orderLabel4.setObjectName(u"orderLabel4")
        self.orderLabel4.setGeometry(QRect(450, 260, 91, 41))
        self.orderLabel4.setFont(font1)
        self.orderLabel4.setStyleSheet(u"color: rgb(33, 123, 88);")
        self.orderLabel4.setText("Jasmine")
        self.orderLabel4.hide()
        self.orderLabel5 = QLabel(self.centralwidget)
        self.orderLabel5.setObjectName(u"orderLabel5")
        self.orderLabel5.setGeometry(QRect(620, 260, 100, 41))
        self.orderLabel5.setFont(font1)
        self.orderLabel5.setStyleSheet(u"color: rgb(33, 123, 88);")
        self.orderLabel5.setText("Red Rice")
        self.orderLabel5.hide()
        self.orderLabel6 = QLabel(self.centralwidget)
        self.orderLabel6.setObjectName(u"orderLabel6")
        self.orderLabel6.setGeometry(QRect(100, 310, 81, 21))
        font2 = QFont()
        font2.setPointSize(12)
        self.orderLabel6.setFont(font2)
        self.orderLabel6.setStyleSheet(u"color: rgb(33, 123, 88);")
        self.orderLabel6.setText("P. 52.00")
        self.orderLabel6.hide()
        self.orderLabel7 = QLabel(self.centralwidget)
        self.orderLabel7.setObjectName(u"orderLabel7")
        self.orderLabel7.setGeometry(QRect(270, 310, 81, 21))
        self.orderLabel7.setFont(font2)
        self.orderLabel7.setStyleSheet(u"color: rgb(33, 123, 88);")
        self.orderLabel7.setText("P. 45.00")
        self.orderLabel7.hide()
        self.orderLabel8 = QLabel(self.centralwidget)
        self.orderLabel8.setObjectName(u"orderLabel8")
        self.orderLabel8.setGeometry(QRect(460, 310, 81, 21))
        self.orderLabel8.setFont(font2)
        self.orderLabel8.setStyleSheet(u"color: rgb(33, 123, 88);")
        self.orderLabel8.setText("P. 48.00")
        self.orderLabel8.hide()
        self.orderLabel9 = QLabel(self.centralwidget)
        self.orderLabel9.setObjectName(u"orderLabel9")
        self.orderLabel9.setGeometry(QRect(640, 310, 81, 21))
        self.orderLabel9.setFont(font2)
        self.orderLabel9.setStyleSheet(u"color: rgb(33, 123, 88);")
        self.orderLabel9.setText("P. 57.00")
        self.orderLabel9.hide()
        
        
        #OrderForm Buttons

        #Product #1
        self.orderPushButton1 = QPushButton(self.centralwidget)
        self.orderPushButton1.setObjectName(u"orderPushButton1")
        self.orderPushButton1.setGeometry(QRect(60, 120, 141, 131))
        icon = QIcon()
        icon.addFile(u"Graphics\Dinorado.png", QSize(), QIcon.Normal, QIcon.Off)
        self.orderPushButton1.setIcon(icon)
        self.orderPushButton1.setIconSize(QSize(140, 140))
        self.orderPushButton1.hide()

        #Product#2
        self.orderPushButton2 = QPushButton(self.centralwidget)
        self.orderPushButton2.setObjectName(u"orderPushButton2")
        self.orderPushButton2.setGeometry(QRect(240, 120, 141, 131))
        icon1 = QIcon()
        icon1.addFile(u"Graphics\Sinandomeng.jpg", QSize(), QIcon.Normal, QIcon.Off)
        self.orderPushButton2.setIcon(icon1)
        self.orderPushButton2.setIconSize(QSize(181, 181))
        self.orderPushButton2.hide()

        #Product#3
        self.orderPushButton3 = QPushButton(self.centralwidget)
        self.orderPushButton3.setObjectName(u"orderPushButton3")
        self.orderPushButton3.setGeometry(QRect(420, 120, 141, 131))
        icon2 = QIcon()
        icon2.addFile(u"Graphics\Jasmine.jpg", QSize(), QIcon.Normal, QIcon.Off)
        self.orderPushButton3.setIcon(icon2)
        self.orderPushButton3.setIconSize(QSize(194, 191))
        self.orderPushButton3.hide()

        #Product#3
        self.orderPushButton4 = QPushButton(self.centralwidget)
        self.orderPushButton4.setObjectName(u"orderPushButton4")
        self.orderPushButton4.setGeometry(QRect(600, 120, 141, 131))
        icon3 = QIcon()
        icon3.addFile(u"Graphics\Red rice.jpg", QSize(), QIcon.Normal, QIcon.Off)
        self.orderPushButton4.setIcon(icon3)
        self.orderPushButton4.setIconSize(QSize(195, 140))
        self.orderPushButton4.hide()
        


        #Dinorado Order Amount
        self.dinoradoHeadLabel = QLabel(self.centralwidget)
        self.dinoradoHeadLabel.setObjectName(u"dinoradoHeadLabel")
        self.dinoradoHeadLabel.setGeometry(QRect(320, 20, 131, 61))       
        self.dinoradoHeadLabel.setText(u"Dinorado") 
        font = QFont()
        font.setPointSize(24)
        self.dinoradoHeadLabel.setFont(font)
        self.dinoradoHeadLabel.setStyleSheet(u"color: rgb(33, 123, 88);")
        self.dinoradoHeadLabel.hide()
        self.dinoradoGraphicsView = QGraphicsView(self.centralwidget)
        self.dinoradoGraphicsView.setObjectName(u"dinoradoGraphicsView")
        self.dinoradoGraphicsView.setGeometry(QRect(79, 110, 201, 201))
        self.dinoradoGraphicsView.setStyleSheet(u"image: url(:/newPrefix/Dinorado.png)")
        self.dinoradoGraphicsView.hide()
        self.dinoradoGroupBox = QGroupBox(self.centralwidget)
        self.dinoradoGroupBox.setObjectName(u"dinoradoGroupBox")
        self.dinoradoGroupBox.setGeometry(QRect(280, 110, 431, 201))
        self.dinoradoGroupBox.hide()
        self.dinoradoLabel = QLabel(self.dinoradoGroupBox)
        self.dinoradoLabel.setObjectName(u"dinoradoLabel")
        self.dinoradoLabel.setGeometry(QRect(30, 10, 81, 31))
        font1 = QFont()
        font1.setPointSize(14)
        self.dinoradoLabel.setFont(font1)
        self.dinoradoLabel.setText("Dinorado") #Change into updatable name
        self.dinoradoLabel.hide()
        self.dinoradoPriceLabel = QLabel(self.dinoradoGroupBox)
        self.dinoradoPriceLabel.setObjectName(u"dinoradoPriceLabel")
        self.dinoradoPriceLabel.setGeometry(QRect(30, 40, 171, 31))
        font2 = QFont()  
        font2.setPointSize(11)
        self.dinoradoPriceLabel.setFont(font2)
        self.dinoradoPriceLabel.setText("P 52.00 per kilogram") #Change into updatable name
        self.dinoradoPriceLabel.hide()
        self.dinoradoSpinBox = QSpinBox(self.dinoradoGroupBox)
        self.dinoradoSpinBox.setObjectName(u"dinoradoSpinBox")
        self.dinoradoSpinBox.setGeometry(QRect(30, 90, 81, 41))
        self.dinoradoSpinBox.hide()
        self.dinoradoTextEdit = QPlainTextEdit(self.dinoradoGroupBox)
        self.dinoradoTextEdit.setObjectName(u"dinoradoTextEdit")
        self.dinoradoTextEdit.setEnabled(True)
        self.dinoradoTextEdit.setGeometry(QRect(290, 30, 104, 41))
        self.dinoradoTextEdit.setReadOnly(True)
        self.dinoradoTextEdit.hide()
        self.dinoradoConfirmButton = QPushButton(self.dinoradoGroupBox)
        self.dinoradoConfirmButton.setObjectName(u"dinoradoConfirmButton")
        self.dinoradoConfirmButton.setGeometry(QRect(300, 150, 91, 31))
        self.dinoradoConfirmButton.setStyleSheet(u"background-color: rgb(66, 107, 31);\n" "color: rgb(240, 240, 240);\n" "font: 10pt \"MS Shell Dlg 2\";")
        self.dinoradoConfirmButton.setText("Confirm")
        self.dinoradoConfirmButton.hide()
        self.dinoradoCancelButton = QPushButton(self.dinoradoGroupBox)
        self.dinoradoCancelButton.setObjectName(u"dinoradoCancelButton")
        self.dinoradoCancelButton.setGeometry(QRect(200, 150, 91, 31))
        self.dinoradoCancelButton.setStyleSheet(u"background-color: rgb(254, 0, 0);\n" "font: 10pt \"MS Shell Dlg 2\";\n" "color: rgb(240, 240, 240);")
        self.dinoradoCancelButton.setText("Cancel")
        self.dinoradoCancelButton.hide()
        self.dinoradoCancelButton.clicked.connect(self.setOrderPage)
        self.dinoradoConfirmButton.clicked.connect(self.setOrderSummary)
        
        #Sinandomeng Order Amount
        self.label = QLabel(self.centralwidget)
        self.label.setObjectName(u"label")
        self.label.setGeometry(QRect(290, 40, 211, 61))
        font = QFont()
        font.setPointSize(24)
        self.label.setFont(font)
        self.label.setStyleSheet(u"color: rgb(33, 123, 88);")
        self.label.setText(u"Sinandomeng")
        self.label.hide()
        self.sinandomengGroupBox = QGroupBox(self.centralwidget)
        self.sinandomengGroupBox.setObjectName(u"sinandomengGroupBox")
        self.sinandomengGroupBox.setGeometry(QRect(281, 120, 431, 201))
        self.sinandomengGroupBox.hide()
        self.sinandomengLabel = QLabel(self.sinandomengGroupBox)
        self.sinandomengLabel.setObjectName(u"sinandomengLabel")
        self.sinandomengLabel.setGeometry(QRect(30, 10, 121, 31))
        self.sinandomengLabel.setText(u"Sinandomeng")
        font1 = QFont()
        font1.setPointSize(14)
        self.sinandomengLabel.setFont(font1)
        self.sinandomengLabel.hide()
        self.sinandomengPrice = QLabel(self.sinandomengGroupBox)
        self.sinandomengPrice.setObjectName(u"sinandomengPrice")
        self.sinandomengPrice.setGeometry(QRect(30, 40, 171, 31))
        self.sinandomengPrice.setText(u"P 45.00 per kilogram")
        font2 = QFont()
        font2.setPointSize(11)
        self.sinandomengPrice.setFont(font2)
        self.sinandomengPrice.hide()
        self.sinandomengSpinBox = QSpinBox(self.sinandomengGroupBox)
        self.sinandomengSpinBox.setObjectName(u"sinandomengSpinBox")
        self.sinandomengSpinBox.setGeometry(QRect(30, 90, 81, 41))
        self.sinandomengSpinBox.hide()
        self.sinandomengTextEdit = QPlainTextEdit(self.sinandomengGroupBox)
        self.sinandomengTextEdit.setObjectName(u"sinandomengTextEdit")
        self.sinandomengTextEdit.setEnabled(True)
        self.sinandomengTextEdit.setGeometry(QRect(290, 30, 104, 41))
        self.sinandomengTextEdit.setReadOnly(True)
        self.sinandomengTextEdit.hide()
        self.sinandomengConfirmButton = QPushButton(self.sinandomengGroupBox)
        self.sinandomengConfirmButton.setObjectName(u"sinandomengConfirmButton")
        self.sinandomengConfirmButton.setGeometry(QRect(300, 150, 91, 31))
        self.sinandomengConfirmButton.setStyleSheet(u"background-color: rgb(66, 107, 31);\n" "color: rgb(240, 240, 240);\n" "font: 10pt \"MS Shell Dlg 2\";")
        self.sinandomengConfirmButton.setText(u"Confirm")
        self.sinandomengCancelButton = QPushButton(self.sinandomengGroupBox)
        self.sinandomengCancelButton.setObjectName(u"sinandomengCancelButton")
        self.sinandomengCancelButton.setGeometry(QRect(200, 150, 91, 31))
        self.sinandomengCancelButton.setStyleSheet(u"background-color: rgb(254, 0, 0);\n""font: 10pt \"MS Shell Dlg 2\";\n""color: rgb(240, 240, 240);")
        self.sinandomengCancelButton.setText(u"Cancel")
        self.sinandomengView = QGraphicsView(self.centralwidget)
        self.sinandomengView.setObjectName(u"sinandomengView")
        self.sinandomengView.setGeometry(QRect(80, 120, 201, 201))
        self.sinandomengView.hide()
        self.sinandomengCancelButton.clicked.connect(self.setOrderPage)
        self.sinandomengConfirmButton.clicked.connect(self.setOrderSummary)
        #jasmine Rice

        #GAWA KA NG CONTAINER TANGINA MO DANN

        self.slabel = QLabel(self.centralwidget)
        self.slabel.setObjectName(u"label")
        self.slabel.setGeometry(QRect(290, 40, 211, 61))
        font = QFont()
        font.setPointSize(24)
        self.slabel.setFont(font)
        self.slabel.setStyleSheet(u"color: rgb(33, 123, 88);")
        self.slabel.setText(u"Sinandomeng")
        self.slabel.hide()
        self.sGroupBox = QGroupBox(self.centralwidget)
        self.sGroupBox.setObjectName(u"sinandomengGroupBox")
        self.sGroupBox.setGeometry(QRect(281, 120, 431, 201))
        self.sGroupBox.hide()
        self.sLabel = QLabel(self.sGroupBox)
        self.sLabel.setObjectName(u"sinandomengLabel")
        self.sLabel.setGeometry(QRect(30, 10, 121, 31))
        self.sLabel.setText(u"Sinandomeng")
        font1 = QFont()
        font1.setPointSize(14)
        self.sLabel.setFont(font1)
        self.sLabel.hide()
        self.sPrice = QLabel(self.sGroupBox)
        self.sPrice.setObjectName(u"sinandomengPrice")
        self.sPrice.setGeometry(QRect(30, 40, 171, 31))
        self.sPrice.setText(u"P 45.00 per kilogram")
        font2 = QFont()
        font2.setPointSize(11)
        self.sPrice.setFont(font2)
        self.sPrice.hide()
        self.sSpinBox = QSpinBox(self.sGroupBox)
        self.sSpinBox.setObjectName(u"sinandomengSpinBox")
        self.sSpinBox.setGeometry(QRect(30, 90, 81, 41))
        self.sSpinBox.hide()
        self.sTextEdit = QPlainTextEdit(self.sGroupBox)
        self.sTextEdit.setObjectName(u"sinandomengTextEdit")
        self.sTextEdit.setEnabled(True)
        self.sTextEdit.setGeometry(QRect(290, 30, 104, 41))
        self.sTextEdit.setReadOnly(True)
        self.sTextEdit.hide()
        self.sConfirmButton = QPushButton(self.sGroupBox)
        self.sConfirmButton.setObjectName(u"sinandomengConfirmButton")
        self.sConfirmButton.setGeometry(QRect(300, 150, 91, 31))
        self.sConfirmButton.setStyleSheet(u"background-color: rgb(66, 107, 31);\n"
"color: rgb(240, 240, 240);\n"
"font: 10pt \"MS Shell Dlg 2\";")
        self.sConfirmButton.setText(u"Confirm")
        self.sCancelButton = QPushButton(self.sGroupBox)
        self.sCancelButton.setObjectName(u"sinandomengCancelButton")
        self.sCancelButton.setGeometry(QRect(200, 150, 91, 31))
        self.sCancelButton.setStyleSheet(u"background-color: rgb(254, 0, 0);\n"
"font: 10pt \"MS Shell Dlg 2\";\n"
"color: rgb(240, 240, 240);")
        self.sCancelButton.setText(u"Cancel")
        self.sView = QGraphicsView(self.centralwidget)
        self.sView.setObjectName(u"sinandomengView")
        self.sView.setGeometry(QRect(80, 120, 201, 201))
        self.sView.hide()

        self.sCancelButton.clicked.connect(self.setOrderPage)
        self.sConfirmButton.clicked.connect(self.setOrderSummary)


        #RED RICE
        self.redRiceGroupBox = QGroupBox(self.centralwidget)
        self.redRiceGroupBox.setObjectName(u"redRiceGroupBox")
        self.redRiceGroupBox.setGeometry(QRect(291, 120, 431, 201))
        self.redRiceLabel = QLabel(self.redRiceGroupBox)
        self.redRiceLabel.setObjectName(u"redRiceLabel")
        self.redRiceLabel.setGeometry(QRect(30, 10, 121, 31))
        font = QFont()
        font.setPointSize(14)
        self.redRiceLabel.setFont(font)
        self.redRiceLabel.setText(u"Red Rice")
        self.redRicePrice = QLabel(self.redRiceGroupBox)
        self.redRicePrice.setObjectName(u"redRicePrice")
        self.redRicePrice.setGeometry(QRect(30, 40, 171, 31))
        font1 = QFont()
        font1.setPointSize(11)
        self.redRicePrice.setFont(font1)
        self.redRicePrice.setText(u"P 80.00 per kilogram")
        self.redRiceSpinBox = QSpinBox(self.redRiceGroupBox)
        self.redRiceSpinBox.setObjectName(u"redRiceSpinBox")
        self.redRiceSpinBox.setGeometry(QRect(30, 90, 81, 41))
        self.redRiceTextEdit = QPlainTextEdit(self.redRiceGroupBox)
        self.redRiceTextEdit.setObjectName(u"redRiceTextEdit")
        self.redRiceTextEdit.setEnabled(True)
        self.redRiceTextEdit.setGeometry(QRect(290, 30, 104, 41))
        self.redRiceTextEdit.setReadOnly(True)
        self.redRiceConfirmButton = QPushButton(self.redRiceGroupBox)
        self.redRiceConfirmButton.setObjectName(u"redRiceConfirmButton")
        self.redRiceConfirmButton.setGeometry(QRect(300, 150, 91, 31))
        self.redRiceConfirmButton.setText(u"Confirm")
        self.redRiceConfirmButton.setStyleSheet(u"background-color: rgb(66, 107, 31);\n""color: rgb(240, 240, 240);\n""font: 10pt \"MS Shell Dlg 2\";")
        self.redRiceCancelButton = QPushButton(self.redRiceGroupBox)
        self.redRiceCancelButton.setObjectName(u"redRiceCancelButton")
        self.redRiceCancelButton.setGeometry(QRect(200, 150, 91, 31))
        self.redRiceCancelButton.setText(u"Cancel")
        self.redRiceCancelButton.setStyleSheet(u"background-color: rgb(254, 0, 0);\n""font: 10pt \"MS Shell Dlg 2\";\n""color: rgb(240, 240, 240);")
        self.redriceHeadLabel = QLabel(self.centralwidget)
        self.redriceHeadLabel.setObjectName(u"redriceHeadLabel")
        self.redriceHeadLabel.setGeometry(QRect(350, 40, 131, 61))
        font2 = QFont()
        font2.setPointSize(24)
        self.redriceHeadLabel.setFont(font2)
        self.redriceHeadLabel.setStyleSheet(u"color: rgb(33, 123, 88);")
        self.redriceHeadLabel.setText(u"Red Rice")
        self.redRiceView = QGraphicsView(self.centralwidget)
        self.redRiceView.setObjectName(u"redRiceView")
        self.redRiceView.setGeometry(QRect(90, 120, 201, 201))
        self.redRiceGroupBox.hide()
        self.redriceHeadLabel.hide()
        self.redRiceView.hide()
        self.redRiceSpinBox.hide()
        self.redRiceTextEdit.hide()
        self.redRiceConfirmButton.hide()
        self.redRiceCancelButton.hide()
        self.redRicePrice.hide()
        self.redRiceLabel.hide()
        self.redRiceCancelButton.clicked.connect(self.setOrderPage)
        self.redRiceConfirmButton.clicked.connect(self.setOrderSummary)
    

        self.retranslateUi(MainWindow)

        QtCore.QMetaObject.connectSlotsByName(MainWindow)
    # setupUi

    def retranslateUi(self, MainWindow):
        _translate = QtCore.QCoreApplication.translate
        MainWindow.setWindowTitle(_translate("MainWindow", u"MainWindow", None))
        self.label2.setText("")
        self.pushButton.setText(_translate("MainWindow", u"Tap to order", None))
        self.pushButton.setText("Tap to Order")

    # retranslateUi

    def hideOrders(self):
        self.dinoradoHeadLabel.hide()
        self.dinoradoGraphicsView.hide()
        self.dinoradoGroupBox.hide()
        self.dinoradoLabel.hide()
        self.dinoradoPriceLabel.hide()
        self.dinoradoSpinBox.hide()
        self.dinoradoTextEdit.hide()
        self.dinoradoConfirmButton.hide()
        self.dinoradoCancelButton.hide()
        self.label.hide()
        self.sinandomengGroupBox.hide()
        self.sinandomengLabel.hide()
        self.sinandomengPrice.hide()
        self.sinandomengSpinBox.hide()
        self.sinandomengTextEdit.hide()
        self.sinandomengConfirmButton.hide()
        self.sinandomengCancelButton.hide()
        self.sinandomengView.hide()
        self.sLabel.hide()
        self.slabel.hide()
        self.sCancelButton.hide()
        self.sConfirmButton.hide()
        self.sTextEdit.hide()
        self.sSpinBox.hide()
        self.sView.hide()
        self.sLabel.hide()
        self.sPrice.hide()
        self.sGroupBox.hide()
        self.redRiceGroupBox.hide()
        self.redriceHeadLabel.hide()
        self.redRiceView.hide()
        self.redRiceSpinBox.hide()
        self.redRiceTextEdit.hide()
        self.redRiceConfirmButton.hide()
        self.redRiceCancelButton.hide()
        self.redRicePrice.hide()
        self.redRiceLabel.hide()

    def setOrderPage(self):
        self.label2.hide()
        self.pushButton.hide()
        self.orderLabel.show()
        self.orderLabel2.show()
        self.orderLabel3.show()
        self.orderLabel4.show()
        self.orderLabel5.show()
        self.orderLabel6.show()
        self.orderLabel7.show()
        self.orderLabel8.show()
        self.orderLabel9.show()
        self.orderPushButton1.show()
        self.orderPushButton2.show()
        self.orderPushButton3.show()
        self.orderPushButton4.show()
        self.hideOrders()
        self.orderPushButton1.clicked.connect(self.setProduct1)
        self.orderPushButton2.clicked.connect(self.setProduct2)
        self.orderPushButton3.clicked.connect(self.setProduct3)
        self.orderPushButton4.clicked.connect(self.setProduct4)
        #print("Clicked")

    def setProduct1(self): #UI_2.1(Dinorado)
        self.label2.hide()
        self.pushButton.hide()
        self.orderLabel.hide()
        self.orderLabel2.hide()
        self.orderLabel3.hide()
        self.orderLabel4.hide()
        self.orderLabel5.hide()
        self.orderLabel6.hide()
        self.orderLabel7.hide()
        self.orderLabel8.hide()
        self.orderLabel9.hide()
        self.orderPushButton1.hide()
        self.orderPushButton2.hide()
        self.orderPushButton3.hide()
        self.orderPushButton4.hide()
        self.dinoradoHeadLabel.show()
        self.dinoradoGraphicsView.show()
        self.dinoradoGroupBox.show()
        self.dinoradoLabel.show()
        self.dinoradoPriceLabel.show()
        self.dinoradoSpinBox.show()
        self.dinoradoTextEdit.show()
        self.dinoradoConfirmButton.show()
        self.dinoradoCancelButton.show()
    
    def setProduct2(self): #UI_2.2 Sinandomeng
        self.label2.hide()
        self.pushButton.hide()
        self.orderLabel.hide()
        self.orderLabel2.hide()
        self.orderLabel3.hide()
        self.orderLabel4.hide()
        self.orderLabel5.hide()
        self.orderLabel6.hide()
        self.orderLabel7.hide()
        self.orderLabel8.hide()
        self.orderLabel9.hide()
        self.orderPushButton1.hide()
        self.orderPushButton2.hide()
        self.orderPushButton3.hide()
        self.orderPushButton4.hide()
        self.label.show()
        self.sinandomengGroupBox.show()
        self.sinandomengLabel.show()
        self.sinandomengPrice.show()
        self.sinandomengSpinBox.show()
        self.sinandomengTextEdit.show()
        self.sinandomengConfirmButton.show()
        self.sinandomengCancelButton.show()
        self.sinandomengView.show()


    def setProduct3(self): #UI_2.3 Jasmine
        self.sLabel.show()
        self.slabel.show()
        self.sCancelButton.show()
        self.sConfirmButton.show()
        self.sTextEdit.show()
        self.sSpinBox.show()
        self.sView.show()
        self.sLabel.show()
        self.sPrice.show()
        self.sGroupBox.show()
        self.label2.hide()
        self.pushButton.hide()
        self.orderLabel.hide()
        self.orderLabel2.hide()
        self.orderLabel3.hide()
        self.orderLabel4.hide()
        self.orderLabel5.hide()
        self.orderLabel6.hide()
        self.orderLabel7.hide()
        self.orderLabel8.hide()
        self.orderLabel9.hide()
        self.orderPushButton1.hide()
        self.orderPushButton2.hide()
        self.orderPushButton3.hide()
        self.orderPushButton4.hide()
        

    def setProduct4(self): #UI_2.4 Red Rice
        self.label2.hide()
        self.pushButton.hide()
        self.orderLabel.hide()
        self.orderLabel2.hide()
        self.orderLabel3.hide()
        self.orderLabel4.hide()
        self.orderLabel5.hide()
        self.orderLabel6.hide()
        self.orderLabel7.hide()
        self.orderLabel8.hide()
        self.orderLabel9.hide()
        self.orderPushButton1.hide()
        self.orderPushButton2.hide()
        self.orderPushButton3.hide()
        self.orderPushButton4.hide()
        self.redRiceGroupBox.show()
        self.redriceHeadLabel.show()
        self.redRiceView.show()
        self.redRiceSpinBox.show()
        self.redRiceTextEdit.show()
        self.redRiceConfirmButton.show()
        self.redRiceCancelButton.show()
        self.redRicePrice.show()
        self.redRiceLabel.show()

    
    def setOrderSummary(self):
        self.hideOrders()
        





        



if __name__ == "__main__":
    app = QApplication(sys.argv)
    MainWindow = QMainWindow()
    ui = Ui_MainWindow()
    ui.setupUi(MainWindow)
    MainWindow.show()
    sys.exit(app.exec())