import sys
from PyQt5.QtCore import *
from PyQt5.QtGui import *
from PyQt5.QtWidgets import *
from PyQt5 import QtWidgets, QtCore
import csv
# import RPi.GPIO as GPIO
# from hx711 import HX711

class Ui_MainWindow(QMainWindow):

    def setupUi(self, MainWindow):

        #Launching the Main Window
        if not MainWindow.objectName():
            MainWindow.setObjectName(u"MainWindow")
        self.setWindowTitle("Grainmate")
        MainWindow.resize(800, 480)
        MainWindow.setTabletTracking(True)
        MainWindow.setAutoFillBackground(False)
        MainWindow.setStyleSheet(u"background-color:rgb(241, 251, 249)")
        MainWindow.setAnimated(True)

        #Landing Page
        self.centralwidget = QWidget(MainWindow)
        self.centralwidget.setObjectName(u"centralwidget")
        self.label2 = QLabel(self.centralwidget)
        self.label2.setObjectName(u"label2")
        self.label2.setGeometry(QRect(50, 90, 631, 171))
        self.label2.setPixmap(QPixmap(u"ricemate.png"))
        self.pushButton = QtWidgets.QPushButton(parent = self.centralwidget)
        self.pushButton.setObjectName(u"pushButton")
        self.pushButton.setText("Tap to continue:")
        self.pushButton.setStyleSheet(u"color: rgb(0,0,0)")
        self.pushButton.setGeometry(QRect(30, 270, 721, 121))
        self.pushButton.clicked.connect(self.setOrderPage)
        font = QFont()
        font.setPointSize(28)
        self.pushButton.setFont(font)
        self.pushButton.setStyleSheet(u"color: rgb(33, 123, 88);")
        self.pushButton.setAutoRepeat(True)
        self.pushButton.setFlat(True)
        self.pushButton_2 = QPushButton(self.centralwidget)
        self.pushButton_2.setObjectName(u"pushButton_2")
        self.pushButton_2.setGeometry(QRect(720, 70, 51, 41))
        self.pushButton_2.setStyleSheet(u"image: url(home.png)")
        self.pushButton_2.setFlat(True)
        self.pushButton_2.clicked.connect(self.setAdminLandingPage)
        MainWindow.setCentralWidget(self.centralwidget)

        #OrderForm
        font = QFont()
        font.setPointSize(24)
        self.orderLabel = QLabel(self.centralwidget)
        self.orderLabel.setObjectName(u"orderLabel")
        self.orderLabel.setGeometry(QRect(290, 70, 231, 41))
        self.orderLabel.setStyleSheet(u"color: rgb(33, 123, 88);")
        self.orderLabel.setText("Select your Rice")
        self.orderLabel.setFont(font)
        self.orderLabel.hide()
        
        font1 = QFont()
        font1.setPointSize(18)
        self.orderLabel2 = QLabel(self.centralwidget)
        self.orderLabel2.setObjectName(u"orderLabel2")
        self.orderLabel2.setGeometry(QRect(80, 290, 111, 41))
        self.orderLabel2.setFont(font1)
        self.orderLabel2.setStyleSheet(u"color: rgb(33, 123, 88);")
        self.orderLabel2.setAlignment(Qt.AlignCenter)
        # self.orderLabel2.setReadOnly(True)
        # self.orderLabel2.setText("Dinorado")
        self.orderLabel2.hide()
        self.orderLabel3 = QLabel(self.centralwidget)
        self.orderLabel3.setObjectName(u"orderLabel3")
        self.orderLabel3.setGeometry(QRect(240, 290, 151, 41))
        self.orderLabel3.setFont(font1)
        self.orderLabel3.setStyleSheet(u"color: rgb(33, 123, 88);")
        self.orderLabel3.setAlignment(Qt.AlignCenter)
        #self.orderLabel3.setReadOnly(True)
        # self.orderLabel3.setText("Sinandomeng")
        self.orderLabel3.hide()
        self.orderLabel4 = QLabel(self.centralwidget)
        self.orderLabel4.setObjectName(u"orderLabel4")
        self.orderLabel4.setGeometry(QRect(440, 290, 100, 41))
        self.orderLabel4.setFont(font1)
        self.orderLabel4.setStyleSheet(u"color: rgb(33, 123, 88);")
        self.orderLabel4.setAlignment(Qt.AlignCenter)
        # self.orderLabel4.setText("Jasmine")
        self.orderLabel4.hide()
        self.orderLabel5 = QLabel(self.centralwidget)
        self.orderLabel5.setObjectName(u"orderLabel5")
        self.orderLabel5.setGeometry(QRect(620, 290, 100, 41))
        self.orderLabel5.setFont(font1)
        self.orderLabel5.setStyleSheet(u"color: rgb(33, 123, 88);")
        self.orderLabel5.setAlignment(Qt.AlignCenter)
        # self.orderLabel5.setText("Red Rice")
        self.orderLabel5.hide()
        self.orderLabel6 = QLabel(self.centralwidget)
        self.orderLabel6.setObjectName(u"orderLabel6")
        self.orderLabel6.setGeometry(QRect(100, 340, 81, 21))
        font2 = QFont()
        font2.setPointSize(10       )
        self.orderLabel6.setFont(font2)
        self.orderLabel6.setStyleSheet(u"color: rgb(33, 123, 88);")
        self.orderLabel6.setAlignment(Qt.AlignCenter)
        # self.orderLabel6.setText("P. 52.00")
        self.orderLabel6.hide()
        self.orderLabel7 = QLabel(self.centralwidget)
        self.orderLabel7.setObjectName(u"orderLabel7")
        self.orderLabel7.setGeometry(QRect(270, 340, 81, 21))
        self.orderLabel7.setFont(font2)
        self.orderLabel7.setStyleSheet(u"color: rgb(33, 123, 88);")
        self.orderLabel7.setAlignment(Qt.AlignCenter)
        # self.orderLabel7.setText("P. 45.00")
        self.orderLabel7.hide()
        self.orderLabel8 = QLabel(self.centralwidget)
        self.orderLabel8.setObjectName(u"orderLabel8")
        self.orderLabel8.setGeometry(QRect(450, 340, 81, 21))
        self.orderLabel8.setFont(font2)
        self.orderLabel8.setStyleSheet(u"color: rgb(33, 123, 88);")
        self.orderLabel8.setAlignment(Qt.AlignCenter)
        # self.orderLabel8.setText("P. 48.00")
        self.orderLabel8.hide()
        self.orderLabel9 = QLabel(self.centralwidget)
        self.orderLabel9.setObjectName(u"orderLabel9")
        self.orderLabel9.setGeometry(QRect(640, 340, 81, 21))
        self.orderLabel9.setFont(font2)
        self.orderLabel9.setStyleSheet(u"color: rgb(33, 123, 88);")
        self.orderLabel9.setAlignment(Qt.AlignCenter)
        # self.orderLabel9.setText("P. 57.00")
        self.orderLabel9.hide()
        
        
        #OrderForm Buttons

        backIcon = QIcon()
        backIcon.addFile(u"Graphics/previous.png", QSize(), QIcon.Normal, QIcon.Off)
        self.adminProductBackButton = QPushButton(self.centralwidget)
        self.adminProductBackButton.setObjectName(u"adminProductBackButton")
        self.adminProductBackButton.setGeometry(QRect(20, 30, 61, 31))
        self.adminProductBackButton.setIcon(backIcon)
        self.adminProductBackButton.setFlat(True)
        self.adminProductBackButton.clicked.connect(self.displayHomePage)
        adminProductBackButtonFont3 = QFont()
        adminProductBackButtonFont3.setPointSize(12)

        #Product #1
        self.orderPushButton1 = QPushButton(self.centralwidget)
        self.orderPushButton1.setObjectName(u"orderPushButton1")
        self.orderPushButton1.setGeometry(QRect(60, 150, 141, 131))
        icon = QIcon()
        icon.addFile(u"Graphics\Dinorado.png", QSize(), QIcon.Normal, QIcon.Off)
        self.orderPushButton1.setIcon(icon)
        self.orderPushButton1.setIconSize(QSize(140, 140))
        self.orderPushButton1.hide()

        #Product#2
        self.orderPushButton2 = QPushButton(self.centralwidget)
        self.orderPushButton2.setObjectName(u"orderPushButton2")
        self.orderPushButton2.setGeometry(QRect(240, 150, 141, 131))
        icon1 = QIcon()
        icon1.addFile(u"Graphics\Sinandomeng.jpg", QSize(), QIcon.Normal, QIcon.Off)
        self.orderPushButton2.setIcon(icon1)
        self.orderPushButton2.setIconSize(QSize(181, 181))
        self.orderPushButton2.hide()

        #Product#3
        self.orderPushButton3 = QPushButton(self.centralwidget)
        self.orderPushButton3.setObjectName(u"orderPushButton3")
        self.orderPushButton3.setGeometry(QRect(420, 150, 141, 131))
        icon2 = QIcon()
        icon2.addFile(u"Graphics\Jasmine.jpg", QSize(), QIcon.Normal, QIcon.Off)
        self.orderPushButton3.setIcon(icon2)
        self.orderPushButton3.setIconSize(QSize(194, 191))
        self.orderPushButton3.hide()

        #Product#4
        self.orderPushButton4 = QPushButton(self.centralwidget)
        self.orderPushButton4.setObjectName(u"orderPushButton4")
        self.orderPushButton4.setGeometry(QRect(600, 150, 141, 131))
        icon3 = QIcon()
        icon3.addFile(u"Graphics\Red rice.jpg", QSize(), QIcon.Normal, QIcon.Off)
        self.orderPushButton4.setIcon(icon3)
        self.orderPushButton4.setIconSize(QSize(195, 140))
        self.orderPushButton4.hide()
        
        


        #Product 1 and General Formats
        self.productTitle1 = QLabel(self.centralwidget)
        self.productTitle1.setObjectName(u"label")
        self.productTitle1.setGeometry(QRect(290, 40, 211, 61))
        font = QFont()
        font.setPointSize(24)
        self.universalGroupBox = QGroupBox(self.centralwidget)
        self.universalGroupBox.setObjectName(u"productGroupBox1")
        self.universalGroupBox.setGeometry(QRect(281, 130, 431, 201))
        self.universalGroupBox.hide()
        self.universalTextEdit = QTextEdit(self.universalGroupBox)
        self.universalTextEdit.setObjectName(u"productTextEdit1")
        self.universalTextEdit.setEnabled(True)
        self.universalTextEdit.setGeometry(QRect(290, 40, 104, 51))
        self.universalTextEdit.setReadOnly(True)
        self.universalTextEdit.setFont(font1)
        self.universalTextEdit.hide()
        self.universalConfirmButton = QPushButton(self.universalGroupBox)
        self.universalConfirmButton.setObjectName(u"productConfirmButton1")
        self.universalConfirmButton.setGeometry(QRect(300, 160, 91, 31))
        self.universalConfirmButton.setStyleSheet(u"background-color: rgb(66, 107, 31);\n" "color: rgb(240, 240, 240);\n" "font: 10pt \"MS Shell Dlg 2\";")
        self.universalConfirmButton.setText(u"Confirm")
        self.universalCancelButton = QPushButton(self.universalGroupBox)
        self.universalCancelButton.setObjectName(u"productCancelButton1")
        self.universalCancelButton.setGeometry(QRect(200, 160, 91, 31))
        self.universalCancelButton.setStyleSheet(u"background-color: rgb(254, 0, 0);\n""font: 10pt \"MS Shell Dlg 2\";\n""color: rgb(240, 240, 240);")
        self.universalCancelButton.setText(u"Cancel")
        self.productTitle1.setFont(font)
        self.productTitle1.setStyleSheet(u"color: rgb(33, 123, 88);")
        self.productTitle1.hide()
        self.productLabel1 = QLabel(self.universalGroupBox)
        self.productLabel1.setObjectName(u"productLabel1")
        self.productLabel1.setGeometry(QRect(30, 20, 121, 31))
        font1 = QFont()
        font1.setPointSize(14)
        self.productLabel1.setFont(font1)
        self.productLabel1.hide()
        self.productPrice1 = QTextEdit(self.universalGroupBox)
        self.productPrice1.setObjectName(u"productPrice1")
        self.productPrice1.setGeometry(QRect(30, 50, 80, 31))
        self.productPrice1.setEnabled(True)
        self.productPrice1.setReadOnly(True)
        font2 = QFont()
        font2.setPointSize(11)
        self.productPrice1.setFont(font2)
        self.productPrice1.hide()
        self.productView1= QGraphicsView(self.centralwidget)
        self.productView1.setObjectName(u"productView1")
        self.productView1.setGeometry(QRect(80, 130, 201, 201))
        self.productView1.hide()
        self.universalCancelButton.clicked.connect(self.setOrderPage)
        self.universalConfirmButton.clicked.connect(self.setOrderSummary)
        self.productSpinBox1 = QDoubleSpinBox(self.universalGroupBox)
        self.productSpinBox1.setObjectName(u"productSpinBox1")
        spinBoxFontSize = QFont()
        spinBoxFontSize.setPointSize(15)
        self.productSpinBox1.setFont(spinBoxFontSize)
        self.productSpinBox1.setGeometry(QRect(30, 100, 81, 41))
        self.productSpinBox1.setMaximum(10)
        self.productSpinBox1.hide()

        self.productSpinBox1.valueChanged.connect(self.displayToTotal1)
        self.productPrice1.textChanged.connect(self.priceToAmount1)

        #Product 2 Order Amount
        self.productTitle2 = QLabel(self.centralwidget)
        self.productTitle2.setObjectName(u"label")
        self.productTitle2.setGeometry(QRect(290, 50, 211, 61))
        self.productTitle2.setFont(font)
        self.productTitle2.setStyleSheet(u"color: rgb(33, 123, 88);")
        self.productTitle2.hide()
        self.productLabel2 = QLabel(self.universalGroupBox)
        self.productLabel2.setObjectName(u"sinandomengLabel")
        self.productLabel2.setGeometry(QRect(30, 20, 121, 31))
        self.productLabel2.setFont(font1)
        self.productLabel2.hide()
        self.productPrice2 = QTextEdit(self.universalGroupBox)
        self.productPrice2.setObjectName(u"sinandomengPrice")
        self.productPrice2.setGeometry(QRect(30, 50, 80, 31))
        self.productPrice2.setEnabled(True)
        self.productPrice2.setReadOnly(True)
        self.productPrice2.setFont(font2)
        self.productPrice2.hide()
        self.productView2 = QGraphicsView(self.centralwidget)
        self.productView2.setObjectName(u"sinandomengView")
        self.productView2.setGeometry(QRect(80, 130, 201, 201))
        self.productView2.hide()
        self.productSpinBox2 = QDoubleSpinBox(self.universalGroupBox)
        self.productSpinBox2.setObjectName(u"productSpinBox2")
        self.productSpinBox2.setFont(spinBoxFontSize)
        self.productSpinBox2.setGeometry(QRect(30, 100, 81, 41))
        self.productSpinBox2.setMaximum(10      )
        self.productSpinBox2.hide()
        self.productPrice2.textChanged.connect(self.priceToAmount2)  
        self.productSpinBox2.valueChanged.connect(self.displayToTotal2)
        self.universalCancelButton.clicked.connect(self.setOrderPage)
        self.universalConfirmButton.clicked.connect(self.setOrderSummary)
        
        #Product 3
        self.productTitle3 = QLabel(self.centralwidget)
        self.productTitle3.setObjectName(u"label")
        self.productTitle3.setGeometry(QRect(290, 50, 211, 61))
        self.productTitle3.setFont(font)
        self.productTitle3.setStyleSheet(u"color: rgb(33, 123, 88);")
        self.productTitle3.hide()
        self.productLabel3 = QLabel(self.universalGroupBox)
        self.productLabel3.setObjectName(u"productLabel3")
        self.productLabel3.setGeometry(QRect(30, 20, 121, 31))
        self.productLabel3.setFont(font1)
        self.productLabel3.hide()
        self.productPrice3 = QTextEdit(self.universalGroupBox)
        self.productPrice3.setObjectName(u"productPrice3")
        self.productPrice3.setGeometry(QRect(30, 50, 80, 31))
        self.productPrice3.setEnabled(True)
        self.productPrice3.setReadOnly(True)
        self.productPrice3.setFont(font2)
        self.productPrice3.hide()
        self.productView3 = QGraphicsView(self.centralwidget)
        self.productView3.setObjectName(u"productView3")
        self.productView3.setGeometry(QRect(80, 130, 201, 201))
        self.productView3.hide()
        self.productSpinBox3 = QDoubleSpinBox(self.universalGroupBox)
        self.productSpinBox3.setObjectName(u"productSpinBox3")
        self.productSpinBox3.setFont(spinBoxFontSize)
        self.productSpinBox3.setGeometry(QRect(30, 100, 81, 41))
        self.productSpinBox3.setMaximum(10      )
        self.productSpinBox3.hide()
        self.productPrice3.textChanged.connect(self.priceToAmount3)  
        self.productSpinBox3.valueChanged.connect(self.displayToTotal3)
        self.universalCancelButton.clicked.connect(self.setOrderPage)
        self.universalConfirmButton.clicked.connect(self.setOrderSummary)


        #Product 4
        self.productTitle4 = QLabel(self.centralwidget)
        self.productTitle4.setObjectName(u"productTitle4")
        self.productTitle4.setGeometry(QRect(350, 50, 131, 61))
        self.productTitle4.setFont(font)
        self.productTitle4.setStyleSheet(u"color: rgb(33, 123, 88);")
        self.productLabel4 = QLabel(self.universalGroupBox)
        self.productLabel4.setObjectName(u"productLabel4")
        self.productLabel4.setGeometry(QRect(30, 20, 121, 31))
        self.productLabel4.setFont(font1)
        self.productPrice4 = QTextEdit(self.universalGroupBox)
        self.productPrice4.setObjectName(u"productPrice4")
        self.productPrice4.setGeometry(QRect(30, 50, 80, 31))
        self.productPrice4.setFont(font2)
        self.productPrice4.setReadOnly(True)
        self.productPrice4.setEnabled(True)
        self.productView4 = QGraphicsView(self.centralwidget)
        self.productView4.setObjectName(u"productView4")
        self.productView4.setGeometry(QRect(90, 130, 201, 201))
        self.productSpinBox4 = QDoubleSpinBox(self.universalGroupBox)
        self.productSpinBox4.setObjectName(u"productSpinBox4")
        self.productSpinBox4.setFont(spinBoxFontSize)
        self.productSpinBox4.setGeometry(QRect(30, 100, 81, 41))
        self.productSpinBox4.setMaximum(10      )
        self.productSpinBox4.hide()
        self.productTitle4.hide()
        self.productView4.hide()
        self.productPrice4.hide()
        self.productLabel4.hide()
        self.universalCancelButton.clicked.connect(self.setOrderPage)
        self.universalConfirmButton.clicked.connect(self.setOrderSummary)
        self.productPrice4.textChanged.connect(self.priceToAmount4)  
        self.productSpinBox4.valueChanged.connect(self.displayToTotal4)

        #OrderSummary
        self.orderSummaryLabelgroupBox = QGroupBox(self.centralwidget)
        self.orderSummaryLabelgroupBox.setObjectName(u"groupBox")
        self.orderSummaryLabelgroupBox.setGeometry(QRect(110, 50, 581, 361))
        self.orderSummaryLabel = QLabel(self.orderSummaryLabelgroupBox)
        self.orderSummaryLabel.setObjectName(u"orderSummaryLabel")
        self.orderSummaryLabel.setGeometry(QRect(50, 50, 261, 51))
        font = QFont()
        font.setPointSize(26)
        self.orderSummaryLabel.setFont(font)
        self.orderSummaryLabel.setText(u"Order Summary")
        self.totalLabel = QLabel(self.orderSummaryLabelgroupBox)
        self.totalLabel.setObjectName(u"totalLabel")
        self.totalLabel.setGeometry(QRect(60, 120, 91, 31))
        font1 = QFont()
        font1.setPointSize(20)
        self.totalLabel.setFont(font1)
        self.totalLabel.setText("Total")
        self.textEdit = QTextEdit(self.orderSummaryLabelgroupBox)
        self.textEdit.setObjectName(u"textEdit")
        self.textEdit.setEnabled(True)
        self.textEdit.setGeometry(QRect(350, 110, 181, 61))
        font2 = QFont()
        font2.setPointSize(22)
        self.textEdit.setFont(font2)
        self.textEdit.setReadOnly(True)
        self.orderConfirmation = QPushButton(self.orderSummaryLabelgroupBox)
        self.orderConfirmation.setObjectName(u"orderConfirmation")
        self.orderConfirmation.setGeometry(QRect(100, 280, 381, 41))
        font3 = QFont()
        font3.setPointSize(10)
        self.orderConfirmation.setFont(font3)
        self.orderConfirmation.setMouseTracking(True)
        self.orderConfirmation.setTabletTracking(True)
        self.orderConfirmation.setStyleSheet(u"background-color: rgb(109, 109, 109); ""\n""color: rgb(241, 251, 249);")
        self.orderConfirmation.setFlat(False)
        self.orderConfirmation.setText("Continue to Payment")
        self.instructionLabel = QLabel(self.orderSummaryLabelgroupBox)
        self.instructionLabel.setObjectName(u"instructionLabel")
        self.instructionLabel.setGeometry(QRect(190, 250, 221, 16))
        self.instructionLabel.setFont(font3)
        self.instructionLabel.setText(u"Please insert the exact amount")
        self.backPushButton = QPushButton(self.orderSummaryLabelgroupBox)
        self.backPushButton.setObjectName(u"pushButton")
        self.backPushButton.setGeometry(QRect(20, 20, 51, 24))
        backIcon = QIcon()
        backIcon.addFile(u"Graphics/previous.png", QSize(), QIcon.Normal, QIcon.Off)
        self.backPushButton.setIcon(backIcon)
        self.backPushButton.setFlat(True)
        self.backPushButton.clicked.connect(self.reminderMessage)
        
        self.orderSummaryLabel.hide()
        self.orderSummaryLabelgroupBox.hide()
        self.textEdit.hide()
        self.orderConfirmation.hide()
        self.instructionLabel.hide()
        self.backPushButton.hide()
        self.totalLabel.hide()


        #Admin Landing Page
        self.adminLogoLabel = QLabel(self.centralwidget)
        self.adminLogoLabel.setObjectName(u"adminLogoLabel")
        self.adminLogoLabel.setGeometry(QRect(50, -10, 701, 291))
        self.adminLogoLabel.setStyleSheet(u"background-image: url(:/newPrefix/ricemate.png);")
        self.adminLogoLabel.setFrameShape(QFrame.NoFrame)
        self.adminLogoLabel.setLineWidth(1)
        self.adminLogoLabel.setPixmap(QPixmap(u"ricemate.png"))
        self.adminLogoLabel.setScaledContents(False)
        adminTextEditFont = QFont()
        adminTextEditFont.setPointSize(12)
        self.adminPasswordLineEdit2 = QLineEdit(self.centralwidget)
        self.adminPasswordLineEdit2.setObjectName(u"adminPasswordLineEdit2")
        self.adminPasswordLineEdit2.setFont(adminTextEditFont)
        self.adminPasswordLineEdit2.setGeometry(QRect(310, 260, 261, 41))
        self.adminPasswordLineEdit2.setPlaceholderText(u"Enter your pin number")
        self.adminPasswordLineEdit2.setEchoMode(QtWidgets.QLineEdit.Password)
        self.adminPasswordLabel2 = QLabel(self.centralwidget)
        self.adminPasswordLabel2.setObjectName(u"adminPasswordLabel2")
        self.adminPasswordLabel2.setGeometry(QRect(200, 270, 101, 21))
        self.adminPasswordLabel2.setFont(adminTextEditFont)
        self.adminPasswordLabel2.setStyleSheet(u"color: rgb(30, 112, 80);")
        self.adminPasswordLabel2.setText("Pin:")

        self.adminTitleLabel = QLabel(self.centralwidget)
        self.adminTitleLabel.setObjectName(u"adminTitleLabel")
        self.adminTitleLabel.setGeometry(QRect(300, 220, 241, 21))
        self.adminTitleLabel.setText("Administrator Mode")
        adminLabelFont2 = QFont()
        adminLabelFont2.setPointSize(15)
        adminLabelFont2.setBold(True)
        self.adminTitleLabel.setFont(adminLabelFont2)
        self.adminTitleLabel.setStyleSheet(u"color: rgb(31, 114, 82)")
        self.adminBackButton = QPushButton(self.centralwidget)
        self.adminBackButton.setObjectName(u"adminBackButton")
        self.adminBackButton.setGeometry(QRect(20, 30, 61, 31))
        self.adminBackButton.setIcon(backIcon)
        self.adminBackButton.setFlat(True)
        self.adminBackButton.clicked.connect(self.displayHomePage)
        adminBackButtonFont3 = QFont()
        adminBackButtonFont3.setPointSize(12)
        self.adminCreateNewAccount = QPushButton(self.centralwidget)
        self.adminCreateNewAccount.setObjectName(u"adminCreateNewAccount")
        self.adminCreateNewAccount.setGeometry(QRect(230, 330, 371, 54))
        self.adminCreateNewAccount.setFont(adminBackButtonFont3)
        self.adminCreateNewAccount.setStyleSheet(u"color: rgb(31, 115, 82);")
        self.adminCreateNewAccount.setFlat(False)
        self.adminCreateNewAccount.setText("Sign in")
        self.adminCreateNewAccount.clicked.connect(self.verifyAccount)

        self.adminPasswordLineEdit2.hide()
        self.adminPasswordLabel2.hide()
        self.adminLogoLabel.hide()
        self.adminTitleLabel.hide()
        self.adminBackButton.hide()
        self.adminCreateNewAccount.hide()
        self.adminProductBackButton.hide()
        

        #Admin Main Menu
        self.adminToLandingPageButton = QPushButton(self.centralwidget)
        self.adminToLandingPageButton.setObjectName(u"adminToLandingPageButton")
        self.adminToLandingPageButton.setGeometry(QRect(20, 30, 61, 31))
        self.adminToLandingPageButton.setIcon(backIcon)
        self.adminToLandingPageButton.setFlat(True)
        self.adminToLandingPageButton.clicked.connect(self.adminReminderMessage)
        self.adminUpdateButton = QPushButton(MainWindow)
        self.adminUpdateButton.setObjectName(u"adminUpdateButton")
        self.adminUpdateButton.setGeometry(QRect(60, 230, 130, 130))
        updateIcon = QIcon()
        updateIcon.addFile(u"Graphics/updateIcon.png", QSize(), QIcon.Normal, QIcon.Off)
        self.adminUpdateButton.setIcon(updateIcon)
        self.adminUpdateButton.setIconSize(QSize(100, 100))
        self.adminUpdateButton.clicked.connect(self.adminUpdateProductDetails)
        self.adminNotificationButton = QPushButton(MainWindow)
        self.adminNotificationButton.setObjectName(u"adminNotificationButton")
        self.adminNotificationButton.setGeometry(QRect(250, 230, 130, 130))
        self.adminNotificationButton.setText(u"Admin Notification")
        self.adminNotificationButton.clicked.connect(self.setAlertSettings)
        self.adminSalesButton = QPushButton(MainWindow)
        self.adminSalesButton.setObjectName(u"adminSalesButton")
        self.adminSalesButton.setGeometry(QRect(430, 230, 130, 130))
        self.adminSalesButton.setText(u"Admin Sales")
        self.adminSalesButton.clicked.connect(self.setSalesData)
        self.adminSecurityButton = QPushButton(MainWindow)
        self.adminSecurityButton.setObjectName(u"adminSecurityButton")
        self.adminSecurityButton.setGeometry(QRect(610, 230, 130, 130))
        self.adminSecurityButton.setText(u"Admin Security")
        self.adminSecurityButton.clicked.connect(self.setPinVerification)
        self.updateLabel = QLabel(MainWindow)
        self.updateLabel.setObjectName(u"updateLabel")
        self.updateLabel.setGeometry(QRect(65, 370, 131, 20))
        self.updateLabel.setStyleSheet(u"color: rgb(31, 114, 82)")
        self.updateLabel.setText(u"Update Product Details")
        self.notificationLabel = QLabel(MainWindow)
        self.notificationLabel.setObjectName(u"notificationLabel")
        self.notificationLabel.setGeometry(QRect(270, 370, 90, 25))
        self.notificationLabel.setText("Rice Notification")
        self.salesDataLabel = QLabel(MainWindow)
        self.salesDataLabel.setObjectName(u"salesDataLabel")
        self.salesDataLabel.setGeometry(QRect(470, 370, 61, 20))
        self.salesDataLabel.setText("Sales Data")
        self.securityLabel = QLabel(MainWindow)
        self.securityLabel.setObjectName(u"securityLabel")
        self.securityLabel.setGeometry(QRect(630, 370, 81, 20))
        self.securityLabel.setText("Rice Security")
        
        self.adminAccountButton = QPushButton(MainWindow)
        self.adminAccountButton.setObjectName(u"adminAccountButton")
        self.adminAccountButton.setGeometry(QRect(710, 30, 51, 41))

        self.adminNotificationButton.hide()
        self.adminUpdateButton.hide()
        self.adminSecurityButton.hide()
        self.adminSalesButton.hide()
        self.updateLabel.hide()
        self.notificationLabel.hide()
        self.salesDataLabel.hide()
        self.securityLabel.hide()
        self.adminAccountButton.hide()
        self.adminToLandingPageButton.hide()


        #adminUpdateProducts
        self.adminUpdateBackButton = QPushButton(self.centralwidget)
        self.adminUpdateBackButton.setObjectName(u"adminUpdateBackButton")
        self.adminUpdateBackButton.setGeometry(QRect(20, 30, 61, 31))
        self.adminUpdateBackButton.setIcon(backIcon)
        self.adminUpdateBackButton.setFlat(True)
        self.adminUpdateBackButton.clicked.connect(self.adminReminderMessage)
        
        #Update Product Template
        # self.backBUtton = QPushButton(MainWindow)
        # self.backBUtton.setObjectName(u"backBUtton")
        # self.backBUtton.setGeometry(QRect(30, 20, 61, 51))
        # font = QFont()
        # font.setPointSize(13)
        # self.backBUtton.setFont(font)
        # self.backBUtton.setStyleSheet(u"image: url(:/newPrefix/Graphics/previous.png)")
        # icon = QIcon()
        # icon.addFile(u"../Graphics/previous.png", QSize(), QIcon.Normal, QIcon.Off)
        # self.backBUtton.setIcon(icon)
        # self.backBUtton.setIconSize(QSize(30, 30))
        # self.backBUtton.setFlat(True)
        self.adminProduct1Label = QLabel(MainWindow)
        self.adminProduct1Label.setObjectName(u"adminProduct1Label")
        self.adminProduct1Label.setGeometry(QRect(210, 169, 141, 41))
        self.adminProduct1Label.setText("Product")
        font2 = QFont()
        font2.setPointSize(20)
        font2.setBold(True)
        adminfont3 = QFont()
        adminfont3.setPointSize(15)
        self.adminProduct1Label.setFont(font2)
        self.adminProduct1Label.setStyleSheet(u"color: rgb(30, 114, 81)")
        self.updateProductName1LineEdit = QLineEdit(MainWindow)
        self.updateProductName1LineEdit.setObjectName(u"updateProductName1LineEdit")
        self.updateProductName1LineEdit.setGeometry(QRect(360, 219, 201, 41))
        self.updateProductName1LineEdit.setFont(adminfont3)
        self.updateProductName1LineEdit.setFrame(True)
        self.updateProductName1LineEdit.setPlaceholderText(u"Enter Product Name")
        self.updateProductPrice1LineEdit = QLineEdit(MainWindow)
        self.updateProductPrice1LineEdit.setObjectName(u"updateProductPrice1LineEdit")
        self.updateProductPrice1LineEdit.setGeometry(QRect(360, 279, 201, 41))
        self.updateProductPrice1LineEdit.setFont(adminfont3)
        self.updateProductPrice1LineEdit.setPlaceholderText(u"Enter Product Price")
        self.adminUpdateProductName1Label = QLabel(MainWindow)
        self.adminUpdateProductName1Label.setObjectName(u"adminUpdateProductName1Label")
        self.adminUpdateProductName1Label.setGeometry(QRect(210, 229, 131, 20))
        self.adminUpdateProductName1Label.setFont(adminfont3)
        self.adminUpdateProductName1Label.setStyleSheet(u"color: rgb(30, 114, 81)")
        self.adminUpdateProductName1Label.setText("Product Name")
        self.adminUpdateProductPrice1Label = QLabel(MainWindow)
        self.adminUpdateProductPrice1Label.setObjectName(u"adminUpdateProductPrice1Label")
        self.adminUpdateProductPrice1Label.setGeometry(QRect(210, 289, 121, 21))
        self.adminUpdateProductPrice1Label.setText("Product Price")
        self.adminUpdateProductPrice1Label.setFont(adminfont3)
        self.adminUpdateProductPrice1Label.setStyleSheet(u"color:rgb(30, 114, 81)")
        self.saveButton = QPushButton(MainWindow)
        self.saveButton.setObjectName(u"saveButton")
        self.saveButton.setGeometry(QRect(480, 339, 75, 24))
        self.saveButton.setStyleSheet(u"background-color: rgb(74, 188, 150);")
        self.saveButton.setText(u"Save")
        self.saveButton.clicked.connect(self.productRiceLabel)
        self.cancelButton = QPushButton(MainWindow)
        self.cancelButton.setObjectName(u"cancelButton")
        self.cancelButton.setGeometry(QRect(390, 339, 75, 24))
        self.cancelButton.setText(u"Cancel")
        self.spinBox = QSpinBox(MainWindow)
        self.spinBox.setObjectName(u"spinBox")
        self.spinBox.setGeometry(QRect(510, 170, 51, 41))
        self.spinBox.setFont(adminfont3)
        self.spinBox.setMinimum(0)
        self.spinBox.setMaximum(4)
                                    
        self.spinBox.hide()
        self.adminProduct1Label.hide()
        self.updateProductName1LineEdit.hide()
        self.updateProductPrice1LineEdit.hide()
        self.adminUpdateProductName1Label.hide()
        self.adminUpdateProductPrice1Label.hide()
        self.saveButton.hide()
        self.cancelButton.hide()

    #Notification System
        #Sales Data 
        self.salesListView = QListView(MainWindow)
        self.salesListView.setObjectName(u"salesListView")
        self.salesListView.setGeometry(QRect(130, 110, 541, 251))
        self.salesDataLabel2 = QLabel(MainWindow)
        self.salesDataLabel2.setObjectName(u"salesDataLabel")
        self.salesDataLabel2.setGeometry(QRect(300, 10, 221, 81))
        salesDataLabelFont = QFont()
        salesDataLabelFont.setPointSize(34)
        self.salesDataLabel2.setFont(salesDataLabelFont)
        self.salesDataLabel2.setStyleSheet(u"color: rgb(29, 108, 77);")
        self.salesDataLabel2.setText("Sales Data")

        self.salesListView.hide()
        self.salesDataLabel2.hide()
        self.adminUpdateBackButton.hide()
        self.adminBackButton.hide()
        self.backPushButton.hide()
        self.adminProductBackButton.hide()

        #Change Pin
        
        self.changePinConfirmButton = QPushButton(MainWindow)
        self.changePinConfirmButton.setObjectName(u"changePinConfirmButton")
        self.changePinConfirmButton.setGeometry(QRect(330, 320, 181, 51))
        self.changePinConfirmButton.setText("Confirm")
        self.changePinConfirmButton.setFont(adminBackButtonFont3)
        self.changePinConfirmButton.setStyleSheet(u"color: rgb(31, 115, 82);")
        self.changePinConfirmButton.clicked.connect(self.pinVerificationConfirmButton)
        self.changePinLineEdit = QLineEdit(MainWindow)
        self.changePinLineEdit.setPlaceholderText("Enter Pin")
        self.changePinLineEdit.setGeometry(QRect(280, 235, 321, 51))
        self.changePinLineEdit.setFont(adminTextEditFont)
        self.changePinLineEdit.setEchoMode(QtWidgets.QLineEdit.Password)
        self.changePinLineEdit.setObjectName(u"changePinLineEdit")
        self.changePinLabel = QLabel(MainWindow)
        self.changePinLabel.setObjectName(u"changePinLlabel")
        self.changePinLabel.setGeometry(QRect(200, 240, 51, 41))
        self.changePinLabel.setText("Pin: ")
        self.changePinLabel.setFont(adminTextEditFont)

        self.changePinConfirmButton.hide()
        self.changePinLineEdit.hide()
        self.changePinLabel.hide()

        
        #Update Pin Password
        self.updatePinLogo = QLabel(self.centralwidget)
        self.updatePinLogo.setObjectName(u"adminLogoLabel")
        self.updatePinLogo.setGeometry(QRect(50, -60, 701, 291))
        self.updatePinLogo.setStyleSheet(u"background-image: url(:/newPrefix/ricemate.png);")
        self.updatePinLogo.setPixmap(QPixmap(u"ricemate.png"))
        self.updatePinPushButton = QPushButton(MainWindow)
        self.updatePinPushButton.setObjectName(u"updatePinPushButton")
        self.updatePinPushButton.setGeometry(QRect(310, 390, 181, 51))
        self.updatePinPushButton.setFont(adminBackButtonFont3)
        self.updatePinPushButton.setStyleSheet("color: rgb(31, 115, 82);")
        self.updatePinPushButton.clicked.connect(self.userUpdatedPinPassword)
        self.updatePinPushButton.setText(u"Update Pin")
        self.updatePinLineEdit = QLineEdit(MainWindow)
        self.updatePinLineEdit.setObjectName(u"updatePinLineEdit")
        self.updatePinLineEdit.setGeometry(QRect(240, 200, 321, 51))
        self.updatePinLineEdit.setFont(adminTextEditFont)
        self.updatePinLineEdit.setPlaceholderText(u"Enter New Pin")
        self.updatePinNewPinLabel = QLabel(MainWindow)
        self.updatePinNewPinLabel.setObjectName(u"updatePinNewPinLabel")
        self.updatePinNewPinLabel.setGeometry(QRect(240, 150, 121, 41))
        self.updatePinNewPinLabel.setFont(adminTextEditFont)
        self.updatePinNewPinLabel.setText(u"New Pin")
        self.updatePinConfirmPinLabel = QLabel(MainWindow)
        self.updatePinConfirmPinLabel.setObjectName(u"updatePinConfirmPinLabel")
        self.updatePinConfirmPinLabel.setGeometry(QRect(240, 270, 151, 41))
        self.updatePinConfirmPinLabel.setFont(adminTextEditFont)
        self.updatePinConfirmPinLabel.setText("Confirm Pin")
        self.updatePinConfirmLineEdit = QLineEdit(MainWindow)
        self.updatePinConfirmLineEdit.setObjectName(u"updatePinConfirmLineEdit")
        self.updatePinConfirmLineEdit.setGeometry(QRect(240, 310, 321, 51))
        self.updatePinConfirmLineEdit.setFont(adminTextEditFont)
        self.updatePinConfirmLineEdit.setPlaceholderText(u"Confirm your Pin")

        self.updatePinPushButton.hide()
        self.updatePinLineEdit.hide()
        self.updatePinConfirmLineEdit.hide()
        self.updatePinNewPinLabel.hide()
        self.updatePinConfirmPinLabel.hide()
        self.updatePinLogo.hide()


        #Alert Setting
        # font = QFont()
        # font.setPointSize(11)
        # Form.setFont(font)
        self.alertSettingLabel = QLabel(MainWindow)
        self.alertSettingLabel.setObjectName(u"alertSettingLabel")
        self.alertSettingLabel.setGeometry(QRect(290, 40, 201, 61))
        alertSettingfont1 = QFont()
        alertSettingfont1.setPointSize(25)
        self.alertSettingLabel.setFont(alertSettingfont1)
        self.alertSettingLabel.setText(u"Alert Setting")
        self.alertSettingItem1 = QLabel(MainWindow)
        self.alertSettingItem1.setObjectName(u"alertSettingItem1")
        self.alertSettingItem1.setGeometry(QRect(110, 140, 201, 16))
        self.alertSettingItem1.setText(u"Turn on Notifications")
        alertSettingfont2 = QFont()
        alertSettingfont2.setPointSize(15)
        self.alertSettingItem1.setFont(alertSettingfont2)
        self.alertSettingItem2 = QLabel(MainWindow)
        self.alertSettingItem2.setObjectName(u"alertSettingItem2")
        self.alertSettingItem2.setGeometry(QRect(110, 170, 261, 31))
        self.alertSettingItem2.setFont(alertSettingfont2)
        self.alertSettingItem2.setText("Near-empty Container Alert")
        self.alertSettingItem3 = QLabel(MainWindow)
        self.alertSettingItem3.setObjectName(u"alertSettingItem3")
        self.alertSettingItem3.setGeometry(QRect(110, 220, 201, 16))
        self.alertSettingItem3.setFont(alertSettingfont2)
        self.alertSettingItem3.setText("Rice Condition Alerts")
        self.alertSettingItem4 = QLabel(MainWindow)
        self.alertSettingItem4.setObjectName(u"alertSettingItem4")
        self.alertSettingItem4.setGeometry(QRect(110, 250, 201, 31))
        self.alertSettingItem4.setFont(alertSettingfont2)
        self.alertSettingItem4.setText("Temperature")
        self.alertSettingItem5 = QLabel(MainWindow)
        self.alertSettingItem5.setObjectName(u"alertSettingItem5")
        self.alertSettingItem5.setGeometry(QRect(110, 290, 201, 31))
        self.alertSettingItem5.setFont(alertSettingfont2)
        self.alertSettingItem5.setText("Humidity")
        self.alertSettingItem6 = QLabel(MainWindow)
        self.alertSettingItem6.setObjectName(u"alertSettingItem6")
        self.alertSettingItem6.setGeometry(QRect(110, 380, 201, 16))
        self.alertSettingItem6.setFont(alertSettingfont2)
        self.alertSettingItem6.setText("Sales Alert")
        self.alertSettingItem7 = QLabel(MainWindow)
        self.alertSettingItem7.setObjectName(u"alertSettingItem7")
        self.alertSettingItem7.setGeometry(QRect(110, 340, 201, 16))
        self.alertSettingItem7.setFont(alertSettingfont2)
        self.alertSettingItem7.setText("Unauthorized Sale")
        self.checkBoxItem1 = QCheckBox(MainWindow)
        self.checkBoxItem1.setObjectName(u"checkBoxItem1")
        self.checkBoxItem1.setGeometry(QRect(500, 140, 75, 20))
        self.checkBoxItem1.setText("Enable")
        self.checkBoxItem2 = QCheckBox(MainWindow)
        self.checkBoxItem2.setObjectName(u"checkBoxItem2")
        self.checkBoxItem2.setGeometry(QRect(500, 180, 75, 20))
        self.checkBoxItem2.setText("Enable")
        self.checkBoxItem3 = QCheckBox(MainWindow)
        self.checkBoxItem3.setObjectName(u"checkBoxItem3")
        self.checkBoxItem3.setGeometry(QRect(500, 220, 75, 20))
        self.checkBoxItem3.setText("Enable")
        self.checkBoxItem4 = QCheckBox(MainWindow)
        self.checkBoxItem4.setObjectName(u"checkBoxItem4")
        self.checkBoxItem4.setGeometry(QRect(500, 260, 75, 20))
        self.checkBoxItem4.setText("Enable")
        self.checkBoxItem5 = QCheckBox(MainWindow)
        self.checkBoxItem5.setObjectName(u"checkBoxItem5")
        self.checkBoxItem5.setGeometry(QRect(500, 300, 75, 20))
        self.checkBoxItem5.setText("Enable")
        self.checkBoxItem6 = QCheckBox(MainWindow)
        self.checkBoxItem6.setObjectName(u"checkBoxItem6")
        self.checkBoxItem6.setGeometry(QRect(500, 340, 75, 20))
        self.checkBoxItem6.setText("Enable")
        self.checkBoxItem7 = QCheckBox(MainWindow)
        self.checkBoxItem7.setObjectName(u"checkBoxItem7")
        self.checkBoxItem7.setGeometry(QRect(500, 380, 75, 20))
        self.checkBoxItem7.setText("Enable")
        self.comboBoxItem2 = QComboBox(MainWindow)
        self.comboBoxItem2.addItem("1 kg")
        self.comboBoxItem2.addItem("2 kg")
        self.comboBoxItem2.addItem("3 kg")
        self.comboBoxItem2.addItem("4 kg")
        self.comboBoxItem2.addItem("5 kg")
        self.comboBoxItem2.setObjectName(u"comboBoxItem2")
        self.comboBoxItem2.setGeometry(QRect(620, 173, 69, 31))
        self.comboBoxItem6 = QComboBox(MainWindow)
        self.comboBoxItem6.addItem("Daily")
        self.comboBoxItem6.addItem("Monthly")
        self.comboBoxItem6.setObjectName(u"comboBoxItem6")
        self.comboBoxItem6.setGeometry(QRect(620, 340, 69, 22))

        self.alertSettingLabel.hide()
        self.alertSettingItem1.hide()
        self.alertSettingItem2.hide()
        self.alertSettingItem3.hide()
        self.alertSettingItem4.hide()
        self.alertSettingItem5.hide()
        self.alertSettingItem6.hide()
        self.alertSettingItem7.hide()
        self.checkBoxItem1.hide()
        self.checkBoxItem2.hide()
        self.checkBoxItem3.hide()
        self.checkBoxItem4.hide()
        self.checkBoxItem5.hide()
        self.checkBoxItem6.hide()
        self.checkBoxItem7.hide()
        self.comboBoxItem2.hide()
        self.comboBoxItem6.hide()
        


        self.retranslateUi(MainWindow)

        QtCore.QMetaObject.connectSlotsByName(MainWindow)
    # setupUi

    def retranslateUi(self, MainWindow):
        _translate = QtCore.QCoreApplication.translate
        MainWindow.setWindowTitle(_translate("MainWindow", u"MainWindow", None))
        self.label2.setText("")
        self.pushButton.setText(_translate("MainWindow", u"Tap to order", None))
        self.pushButton.setText("Tap to Order")

    # retranslateUi



    def priceToAmount1(self): #price of the product#1
        priceBox = self.sender()
        priceValue = priceBox.toPlainText()
        self.userPrice1 = float(priceValue)
    
    def priceToAmount2(self): #price of the product#2
        priceBox = self.sender()
        priceValue = priceBox.toPlainText()
        self.userPrice2 = int(priceValue)

    def priceToAmount3(self): #price of the product#3
        priceBox = self.sender()
        priceValue = priceBox.toPlainText()
        self.userPrice3 = float(priceValue)

    def priceToAmount4(self): #price of the product#4
        priceBox = self.sender()
        priceValue = priceBox.toPlainText()
        self.userPrice4 = float(priceValue)

    def displayToTotal1(self): #amount bought by the buyer in product#1
        spinbox1 = self.sender()
        value = spinbox1.value() * self.userPrice1
        self.universalTextEdit.setText(str(int(value)))
        self.textEdit.setText(str(int(value)))

    def displayToTotal2(self): #amount bought by the buyer in product#2
        spinbox2 = self.sender()
        value = spinbox2.value() * self.userPrice2
        self.universalTextEdit.setText(str(int(value)))
        self.textEdit.setText(str(int(value)))

    def displayToTotal3(self): #amount bought by the buyer in product#3
        spinbox3 = self.sender()
        value = spinbox3.value() * self.userPrice3
        self.universalTextEdit.setText(str(int(value)))
        self.textEdit.setText(str(int(value)))

    def displayToTotal4(self): #amount bought by the buyer in product#4
        spinbox4 = self.sender()
        value = spinbox4.value() * self.userPrice4
        self.universalTextEdit.setText(str(int(value)))
        self.textEdit.setText(str(int(value)))

    def displayHomePage(self):
        self.hideOrders()
        self.label2.show()
        self.pushButton.show()
        self.pushButton_2.show()
        self.adminPasswordLineEdit2.hide()
        self.adminPasswordLabel2.hide()
        self.adminPasswordLineEdit2.clear()
        self.adminLogoLabel.hide()
        self.adminTitleLabel.hide()
        self.adminBackButton.hide()
        self.adminCreateNewAccount.hide()
        self.salesListView.hide()
        self.salesDataLabel2.hide()
        self.adminUpdateBackButton.hide()
        self.adminBackButton.hide()
        self.backPushButton.hide()
        self.spinBox.hide()
        self.adminProduct1Label.hide()
        self.updateProductName1LineEdit.hide()
        self.updateProductPrice1LineEdit.hide()
        self.adminUpdateProductName1Label.hide()
        self.adminUpdateProductPrice1Label.hide()
        self.saveButton.hide()
        self.cancelButton.hide()
        self.adminProductBackButton.hide()
        self.orderLabel.hide()
        self.orderLabel2.hide()
        self.orderLabel3.hide()
        self.orderLabel4.hide()
        self.orderLabel5.hide()
        self.orderLabel6.hide()
        self.orderLabel7.hide()
        self.orderLabel8.hide()
        self.orderLabel9.hide()
        self.orderPushButton1.hide()
        self.orderPushButton2.hide()
        self.orderPushButton3.hide()
        self.orderPushButton4.hide()
        
    
    def reminderMessage(self):
        reminder = QMessageBox(self)
        reminder.setWindowTitle("Notice")
        reminder.setText("Pressing YES will cancel your transaction. Everything will not be saved.")
        reminder.setStandardButtons(QMessageBox.Yes | QMessageBox.No)
        reminder.setIcon(QMessageBox.Warning)
        button = reminder.exec()

        if button == QMessageBox.Yes:
            print("Yes!")
            self.displayHomePage()
        else:
            print("No!")

    def verifyAccount(self):
        password = self.adminPasswordLineEdit2.text()
        with open('PythonNiUI\CSVFiles\password.csv', 'r') as csv:
            data = [[x.strip() for x in line.strip().split(',')] for line in csv.readlines()][-1]
            pin = data[0]
        if password == pin:
            print("Logged In")
            self.setAdminMainMenu()

        else:
            invalidMessage = QMessageBox(self)
            invalidMessage.setWindowTitle("Invalid Input")
            invalidMessage.setText("You entered an invalid account username or password")
            invalidMessage.setStandardButtons(QMessageBox.Ok)
            invalidMessage.setIcon(QMessageBox.Warning)
            asdf = invalidMessage.exec()
            self.adminPasswordLineEdit2.clear()
            print("Invalid username or password")

    def hideOrders(self): #hide orders when clicking back/ cancel
        self.productTitle1.hide()
        self.productView1.hide()
        self.productLabel1.hide()
        self.productTitle2.hide()
        self.universalGroupBox.hide()
        self.productLabel2.hide()
        self.productPrice2.hide()
        self.productSpinBox1.hide()
        self.productSpinBox2.hide()
        self.productSpinBox3.hide()
        self.productSpinBox4.hide()
        self.universalTextEdit.hide()
        self.universalConfirmButton.hide()
        self.universalCancelButton.hide()
        self.productView2.hide()
        self.productTitle3.hide()
        self.productLabel3.hide()
        self.productView3.hide()
        self.productPrice3.hide()
        self.productTitle4.hide()
        self.productView4.hide()
        self.productPrice4.hide()
        self.productLabel4.hide()
        self.orderSummaryLabelgroupBox.hide()

        self.adminUpdateButton.hide()
        self.adminNotificationButton.hide()
        self.adminSecurityButton.hide()
        self.adminSalesButton.hide()
        self.updateLabel.hide()
        self.notificationLabel.hide()
        self.salesDataLabel.hide()
        self.securityLabel.hide()
        self.adminAccountButton.hide()  

    def hideMainMenus(self):
        self.label2.hide()
        self.pushButton.hide()
        self.pushButton_2.hide()

    def setOrderPage(self): #MainMenue page
        self.hideOrders()
        self.hideMainMenus()
        self.adminBackButton.hide()
        self.adminProductBackButton.hide()
        self.adminProductBackButton.show()
        self.orderLabel.show()
        self.orderLabel2.show()
        self.orderLabel3.show()
        self.orderLabel4.show()
        self.orderLabel5.show()
        self.orderLabel6.show()
        self.orderLabel7.show()
        self.orderLabel8.show()
        self.orderLabel9.show()
        self.orderPushButton1.show()
        self.orderPushButton2.show()
        self.orderPushButton3.show()
        self.orderPushButton4.show()
        self.clearInputs()
        self.orderPushButton1.clicked.connect(self.setProduct1)
        self.orderPushButton2.clicked.connect(self.setProduct2)
        self.orderPushButton3.clicked.connect(self.setProduct3)
        self.orderPushButton4.clicked.connect(self.setProduct4)

        #Read CSV
        with open('PythonNiUI\CSVFiles\product#1NameAndPrice.csv', 'r') as csv:
            data = [[x.strip() for x in line.strip().split(',')] for line in csv.readlines()][-1]
            # print(data)
            loadProductLabel1 = data[0]
            loadProductPrice1 = data[1]
            print(loadProductLabel1, loadProductPrice1)
            self.orderLabel2.setText(loadProductLabel1)
            self.orderLabel6.setText(loadProductPrice1)
            self.productPrice1.setText(loadProductPrice1)
            self.productTitle1.setText(loadProductLabel1)
            self.productLabel1.setText(loadProductLabel1)

        with open('PythonNiUI\CSVFiles\product#2NameAndPrice.csv', 'r') as csv:
            data = [[x.strip() for x in line.strip().split(',')] for line in csv.readlines()][-1]
            loadProductLabel2 = data[0]
            loadProductPrice2 = data[1]
            self.productPrice2.setText(loadProductPrice2)
            self.orderLabel3.setText(loadProductLabel2)
            self.orderLabel7.setText(loadProductPrice2)
            self.productTitle2.setText(loadProductLabel2)
            self.productLabel2.setText(loadProductLabel2)

        with open('PythonNiUI\CSVFiles\product#3NameAndPrice.csv', 'r') as csv:
            data = [[x.strip() for x in line.strip().split(',')] for line in csv.readlines()][-1]
            loadProductLabel3 = data[0]
            loadProductPrice3 = data[1]
            self.productPrice3.setText(loadProductPrice3)
            self.orderLabel4.setText(loadProductLabel3)
            self.orderLabel8.setText(loadProductPrice3)
            self.productTitle3.setText(loadProductLabel3)
            self.productLabel3.setText(loadProductLabel3)

        with open('PythonNiUI\CSVFiles\product#4NameAndPrice.csv', 'r') as csv:
            data = [[x.strip() for x in line.strip().split(',')] for line in csv.readlines()][-1]
            loadProductLabel4 = data[0]
            loadProductPrice4 = data[1]
            self.productPrice4.setText(loadProductPrice4)
            self.orderLabel5.setText(loadProductLabel4)
            self.orderLabel9.setText(loadProductPrice4)
            self.productTitle4.setText(loadProductLabel4)
            self.productLabel4.setText(loadProductLabel4)
        #     print(data)
        
        #Order Summary
        self.orderSummaryLabel.hide()
        self.orderSummaryLabelgroupBox.hide()
        self.textEdit.hide()
        self.orderConfirmation.hide()
        self.instructionLabel.hide()
        self.totalLabel.hide()

    def clearInputs(self):  # Clear Total and Amount fields 
        self.universalTextEdit.clear()
        self.productSpinBox1.clear()
        self.productSpinBox2.clear()
        self.productSpinBox3.clear()
        self.productSpinBox4.clear()
        self.textEdit.clear()

    def setProduct1(self): # UI_2.Product1
        self.label2.hide()
        self.pushButton.hide()
        self.orderLabel.hide()
        self.orderLabel2.hide()
        self.orderLabel3.hide()
        self.orderLabel4.hide()
        self.orderLabel5.hide()
        self.orderLabel6.hide()
        self.orderLabel7.hide()
        self.orderLabel8.hide()
        self.orderLabel9.hide()
        self.orderPushButton1.hide()
        self.orderPushButton2.hide()
        self.orderPushButton3.hide()
        self.orderPushButton4.hide()
        self.productTitle1.show()
        self.productView1.show()
        self.productLabel1.show()
        self.productPrice1.show()
        self.productView1.show()
        self.productSpinBox1.show()
        self.showUniversalGroupBox()
        self.pushButton_2.hide()
          
    def setProduct2(self): # UI_2.Product2
        self.label2.hide()
        self.pushButton.hide()
        self.orderLabel.hide()
        self.orderLabel2.hide()
        self.orderLabel3.hide()
        self.orderLabel4.hide()
        self.orderLabel5.hide()
        self.orderLabel6.hide()
        self.orderLabel7.hide()
        self.orderLabel8.hide()
        self.orderLabel9.hide()
        self.orderPushButton1.hide()
        self.orderPushButton2.hide()
        self.orderPushButton3.hide()
        self.orderPushButton4.hide()
        self.productTitle2.show()
        self.productView2.show()
        self.productLabel2.show()
        self.productPrice2.show()
        self.productSpinBox2.show()
        self.showUniversalGroupBox()
        self.pushButton_2.hide()
  
    def setProduct3(self): # UI_2.Product3
        self.productTitle3.show()
        self.productView3.show()
        self.productLabel3.show()
        self.productPrice3.show()
        self.productSpinBox3.show()
        self.showUniversalGroupBox()
        self.label2.hide()
        self.pushButton.hide()
        self.orderLabel.hide()
        self.orderLabel2.hide()
        self.orderLabel3.hide()
        self.orderLabel4.hide()
        self.orderLabel5.hide()
        self.orderLabel6.hide()
        self.orderLabel7.hide()
        self.orderLabel8.hide()
        self.orderLabel9.hide()
        self.orderPushButton1.hide()
        self.orderPushButton2.hide()
        self.orderPushButton3.hide()
        self.orderPushButton4.hide()
        self.pushButton_2.hide()
        
    def setProduct4(self): # UI_2.Product4
        self.label2.hide()
        self.pushButton.hide()
        self.orderLabel.hide()
        self.orderLabel2.hide()
        self.orderLabel3.hide()
        self.orderLabel4.hide()
        self.orderLabel5.hide()
        self.orderLabel6.hide()
        self.orderLabel7.hide()
        self.orderLabel8.hide()
        self.orderLabel9.hide()
        self.orderPushButton1.hide()
        self.orderPushButton2.hide()
        self.orderPushButton3.hide()
        self.orderPushButton4.hide()
        self.productTitle4.show()
        self.productView4.show()
        self.productLabel4.show()
        self.productPrice4.show()
        self.productSpinBox4.show()
        self.showUniversalGroupBox()
        self.pushButton_2.hide()

    def setOrderSummary(self):  #Order Summary going to Payment
        self.hideOrders()
        self.adminProductBackButton.hide()
        self.orderSummaryLabel.show()
        self.orderSummaryLabelgroupBox.show()
        self.textEdit.show()
        self.orderConfirmation.show()
        self.instructionLabel.show()
        self.backPushButton.show()
        self.totalLabel.show()
        self.pushButton_2.hide()

    def showUniversalGroupBox(self):    #Orders universal group box
        self.universalGroupBox.show()
        self.universalTextEdit.show()
        self.universalConfirmButton.show()
        self.universalCancelButton.show()  

    def setAdminLandingPage(self):  #Admin Landing page UI
        self.label2.hide()
        self.pushButton.hide()
        self.pushButton_2.hide()
        self.adminPasswordLineEdit2.show()
        self.adminPasswordLineEdit2.clear()
        self.adminPasswordLabel2.show()
        self.adminLogoLabel.show()
        self.adminTitleLabel.show()
        self.adminBackButton.show()
        self.adminCreateNewAccount.show()
        self.updateLabel.hide()
        self.adminUpdateButton.hide()
        self.adminNotificationButton.hide()
        self.adminSecurityButton.hide()
        self.adminSalesButton.hide()
        self.notificationLabel.hide()
        self.salesDataLabel.hide()
        self.securityLabel.hide()
        self.adminAccountButton.hide()
        self.adminUpdateBackButton.hide()
        self.spinBox.hide()
        self.adminProduct1Label.hide()
        self.updateProductName1LineEdit.hide()
        self.updateProductPrice1LineEdit.hide()
        self.adminUpdateProductName1Label.hide()
        self.adminUpdateProductPrice1Label.hide()
        self.saveButton.hide()
        self.cancelButton.hide()
        self.salesListView.hide()
        self.salesDataLabel2.hide()
        self.adminProductBackButton.hide()
        self.changePinConfirmButton.hide()
        self.changePinLineEdit.hide()
        self.changePinLabel.hide()
        self.updatePinPushButton.hide()
        self.updatePinLineEdit.hide()
        self.updatePinConfirmLineEdit.hide()
        self.updatePinNewPinLabel.hide()
        self.updatePinConfirmPinLabel.hide()
        self.updatePinLogo.hide()
        self.hideAlertSettings()


        
    
    def adminReminderMessage(self): #To Back to Admin Landing Page - login form
        adminReminder = QMessageBox(self)
        adminReminder.setWindowTitle("Notice")
        adminReminder.setText("Pressing YES will return you to login form. Everything will not be saved.")
        adminReminder.setStandardButtons(QMessageBox.Yes | QMessageBox.No)
        adminReminder.setIcon(QMessageBox.Warning)
        adminButton = adminReminder.exec()

        if adminButton == QMessageBox.Yes:
            print("Yes!")
            self.setAdminLandingPage()
        else:
            print("No!")
        
    def setAdminMainMenu(self): #Admin Main Menu (Update Products, Unregistered Sales, Sales Data)
        self.adminUpdateButton.show()
        self.adminSecurityButton.show()
        self.adminSalesButton.show()
        self.adminNotificationButton.show()
        self.updateLabel.show()
        self.notificationLabel.show()
        self.salesDataLabel.show()
        self.securityLabel.show()
        self.adminAccountButton.show()
        self.adminPasswordLineEdit2.hide()
        self.adminPasswordLabel2.hide()
        self.adminLogoLabel.show()
        self.adminTitleLabel.hide()
        self.adminUpdateBackButton.show()
        self.adminCreateNewAccount.hide()
        self.changePinConfirmButton.hide()
        self.changePinLineEdit.hide()
        self.changePinLabel.hide()
        self.updatePinLogo.hide()


    def adminUpdateProductDetails(self):    #Update Products
        self.adminProduct1Label.show()
        self.updateProductName1LineEdit.show()
        self.updateProductPrice1LineEdit.show()
        self.adminUpdateProductName1Label.show()
        self.adminUpdateProductPrice1Label.show()
        self.adminLogoLabel.show()
        self.saveButton.show()
        self.cancelButton.show()
        self.spinBox.show()
        self.hideAdminMainMenu()
        self.adminUpdateButton.hide()
        self.adminNotificationButton.hide()
        self.adminSecurityButton.hide()
        self.adminSalesButton.hide()
        self.updateLabel.hide()
        self.notificationLabel.hide()
        self.salesDataLabel.hide()
        self.securityLabel.hide()
        self.updatePinLogo.show()
        self.adminLogoLabel.hide()

        # self.adminAccountButton.hide()

    def hideAdminMainMenu(self): #Hide the contents of admin main menu
        self.adminUpdateButton.hide()
        self.adminNotificationButton.hide()
        self.adminSecurityButton.hide()
        self.adminSalesButton.hide()
        self.notificationLabel.hide()
        self.salesDataLabel.hide()
        self.securityLabel.hide()
        self.adminAccountButton.hide()
        self.adminPasswordLineEdit2.hide()
        self.adminPasswordLabel2.hide()
        self.adminLogoLabel.show()
        self.adminTitleLabel.hide()
        self.adminBackButton.show()
        self.adminCreateNewAccount.hide()
        self.adminProductBackButton.hide()
        self.changePinConfirmButton.hide()
        self.changePinLineEdit.hide()
        self.changePinLabel.hide()
        self.updatePinPushButton.hide()
        self.updatePinLineEdit.hide()
        self.updatePinConfirmLineEdit.hide()
        self.updatePinNewPinLabel.hide()
        self.updatePinConfirmPinLabel.hide()


    def setSalesData(self): #Show the contents of the Sales Data UI
        self.hideAdminMainMenu()
        self.adminLogoLabel.hide()
        self.salesListView.show()
        self.salesDataLabel2.show()
        self.adminUpdateBackButton.show()
        self.label2.hide()
        self.pushButton.hide()
        self.pushButton_2.hide()
        self.updateLabel.hide ()
        
    def productRiceLabel(self): #Calls UpdateProductFunctions in every spinbox
        if self.spinBox.value() == 1:
            self.getItemInProduct1DetailCSV()

        elif self.spinBox.value() == 2:
            self.getItemInProduct2DetailCSV()

        elif self.spinBox.value() == 3:
            self.getItemInProduct3DetailCSV()

        elif self.spinBox.value() == 4:
            self.getItemInProduct4DetailCSV()


    def getItemInProduct1DetailCSV(self): #Product#1
            updatedProductLabel = self.sender()
            updatedProductLabel = self.updateProductName1LineEdit.text()
            updatedProductPrice = self.sender()
            updatedProductPrice = self.updateProductPrice1LineEdit.text()
            data_to_append = [
                [updatedProductLabel, updatedProductPrice],
            ]

            file = open('PythonNiUI\CSVFiles\product#1NameAndPrice.csv', 'a', newline='')
            writer = csv.writer(file)
            writer.writerows(data_to_append)
            file.close()

    def getItemInProduct2DetailCSV(self): #Product#2
        updatedProductLabel = self.sender()
        updatedProductLabel = self.updateProductName1LineEdit.text()
        updatedProductPrice = self.sender()
        updatedProductPrice = self.updateProductPrice1LineEdit.text()
        data_to_append = [
            [updatedProductLabel, updatedProductPrice],
        ]

        file = open('PythonNiUI\CSVFiles\product#2NameAndPrice.csv', 'a', newline='')
        writer = csv.writer(file)
        writer.writerows(data_to_append)
        file.close()

    def getItemInProduct3DetailCSV(self): #Product#3
        updatedProductLabel = self.sender()
        updatedProductLabel = self.updateProductName1LineEdit.text()
        updatedProductPrice = self.sender()
        updatedProductPrice = self.updateProductPrice1LineEdit.text()
        data_to_append = [
            [updatedProductLabel, updatedProductPrice],
        ]

        file = open('PythonNiUI\CSVFiles\product#3NameAndPrice.csv', 'a', newline='')
        writer = csv.writer(file)
        writer.writerows(data_to_append)
        file.close()

    def getItemInProduct4DetailCSV(self): #Product#4
            updatedProductLabel = self.sender()
            updatedProductLabel = self.updateProductName1LineEdit.text()
            updatedProductPrice = self.sender()
            updatedProductPrice = self.updateProductPrice1LineEdit.text()
            data_to_append = [
                [updatedProductLabel, updatedProductPrice],
            ]

            file = open('PythonNiUI\CSVFiles\product#4NameAndPrice.csv', 'a', newline='')
            writer = csv.writer(file)
            writer.writerows(data_to_append)
            file.close()

    def setPinVerification(self):
        self.changePinConfirmButton.show()
        self.changePinLineEdit.show()
        self.changePinLabel.show()
        self.adminNotificationButton.hide()
        self.adminUpdateButton.hide()
        self.adminSecurityButton.hide()
        self.adminSalesButton.hide()
        self.updateLabel.hide()
        self.notificationLabel.hide()
        self.salesDataLabel.hide()
        self.securityLabel.hide()
        self.adminAccountButton.hide()
        self.adminToLandingPageButton.hide()

    def setUpdatePinPassword(self):
        self.updatePinPushButton.show()
        self.updatePinLineEdit.show()
        self.updatePinConfirmLineEdit.show()
        self.updatePinNewPinLabel.show()
        self.updatePinConfirmPinLabel.show()
        self.updatePinLogo.show()
        self.changePinConfirmButton.hide()
        self.changePinLineEdit.hide()
        self.changePinLabel.hide()
        self.adminLogoLabel.hide()

    def userUpdatedPinPassword(self):
        updatedPinLabel= self.sender()
        updatedPinLabel = self.updatePinLineEdit.text()
        finalUpdatedPinLabel = self.sender()
        finalUpdatedPinLabel = self.updatePinConfirmLineEdit.text()

        if updatedPinLabel == finalUpdatedPinLabel:
            pinPasswords = [
                [finalUpdatedPinLabel],
            ]

            file = open('PythonNiUI\CSVFiles\password.csv', 'a', newline='')
            writer = csv.writer(file)
            writer.writerows(pinPasswords)
            file.close()

    # def checkUpdatedPinPassword(self):
    #     with open('PythonNiUI\password.csv', 'r') as csv:
    #         data = [[x.strip() for x in line.strip().split(',')] for line in csv.readlines()][-1]
    #         print(data)

    def pinVerificationConfirmButton(self): #use CSV to store the updated passwords
        with open('PythonNiUI\CSVFiles\password.csv', 'r') as csv:
            data = [[x.strip() for x in line.strip().split(',')] for line in csv.readlines()][-1]
            pin = data[0]
        if self.changePinLineEdit.text() == pin:
            self.setUpdatePinPassword()

            # updatedPinPassword = self.sender()
            # updatedPinPassword = self.changePinLineEdit.text()

    def setAlertSettings(self): #Notifications
        self.alertSettingLabel.show()
        self.alertSettingItem1.show()
        self.alertSettingItem2.show()
        self.alertSettingItem3.show()
        self.alertSettingItem4.show()
        self.alertSettingItem5.show()
        self.alertSettingItem6.show()
        self.alertSettingItem7.show()
        self.checkBoxItem1.show()
        self.checkBoxItem2.show()
        self.checkBoxItem3.show()
        self.checkBoxItem4.show()
        self.checkBoxItem5.show()
        self.checkBoxItem6.show()
        self.checkBoxItem7.show()
        self.comboBoxItem2.show()
        self.comboBoxItem6.show()
        self.hideAdminMainMenu()
        self.adminLogoLabel.hide()
        self.label2.hide()
        self.pushButton.hide()
        self.pushButton_2.hide()
        self.updateLabel.hide()
    
    def hideAlertSettings(self):
        self.alertSettingLabel.hide()
        self.alertSettingItem1.hide()
        self.alertSettingItem2.hide()
        self.alertSettingItem3.hide()
        self.alertSettingItem4.hide()
        self.alertSettingItem5.hide()
        self.alertSettingItem6.hide()
        self.alertSettingItem7.hide()
        self.checkBoxItem1.hide()
        self.checkBoxItem2.hide()
        self.checkBoxItem3.hide()
        self.checkBoxItem4.hide()
        self.checkBoxItem5.hide()
        self.checkBoxItem6.hide()
        self.checkBoxItem7.hide()
        self.comboBoxItem2.hide()
        self.comboBoxItem6.hide()
        

if __name__ == "__main__":
    app = QApplication(sys.argv)
    MainWindow = QMainWindow()
    ui = Ui_MainWindow()
    ui.setupUi(MainWindow)
    MainWindow.show()
    sys.exit(app.exec())